<?php
/* @var $noReply Forum_Model_Forum
 * @var $forumItemsQuestion Forum_Model_Forum
 * @var $itemsReply Forum_Model_Forum
 */
$this->title = 'Форум';
//$this->secondary_text = 'Список категорий';
$this->headScript()
    ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
    ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js');

?>
<?php if($this->no_reply):?>
    <h3>Без ответа</h3>
    <div class="col-lg-offset-1">
        <?php foreach ($this->no_reply as $noReply):?>
            <div class="panel panel-default" id="question<?=$noReply->getId();?>">
                <div class="panel-heading clearfix">
                    <em><u><?=date("d.m.Y", strtotime($noReply->getTimestamp()));?></u> г.,</em>
                    <strong><?=$noReply->getAuthor();?></strong> (<?=$noReply->getCategory();?>)

                    <div class="btn-group btn-group-sm pull-right" role="group" aria-label="..."  id="<?=$noReply->getId();?>">
                        <button type="button" class="btn btn-success reply-forum" data-action="reply">
                            <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                        </button>
                        <?php if($this->user->role == 'admin'):?>
                            <button type="button" class="btn btn-danger delete-forum" data-action="delete">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        <?php endif;?>
                    </div>
                </div>
                <div class="panel-body">
                    <?=$noReply->getContent();?>
                </div>
            </div>
        <?php endforeach;?>

    </div>
<?php endif;?>
<hr/>
<?php if($this->forums):?>
    <div class="row">
        <div class="col-md-7"><h3>С ответами</h3></div>
        <div class="col-md-5"><?= $this->render('components/_paginator.phtml')?></div>
    </div>
    <div class="col-lg-offset-1">
        <?php foreach ($this->forums as $forumItems):?>
            <?php $forumItemsQuestion = $forumItems['question'];?>
            <div class="panel panel-default" id="question<?=$forumItemsQuestion->getId();?>">
                <div class="panel-heading clearfix">
                    <em><u><?=date("d.m.Y", strtotime($forumItemsQuestion->getTimestamp()));?></u> г.,</em>
                    <strong><?=$forumItemsQuestion->getAuthor();?></strong> (<?=$forumItemsQuestion->getCategory();?>)

                    <div class="btn-group btn-group-sm pull-right"
                         role="group"
                         aria-label="..."
                         id="<?=$forumItemsQuestion->getId();?>">
                        <button type="button" class="btn btn-success reply-forum" data-action="reply">
                            <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                        </button>
                        <?php if($this->user->role == 'admin'):?>
                            <button type="button" class="btn btn-danger delete-forum" data-action="delete">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        <?php endif;?>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="mb2">
                        <?=$forumItemsQuestion->getContent();?>
                    </div>
                    <?php foreach ($forumItems['reply'] as $itemsReply):?>
                        <div class="col-md-offset-1">
                            <div class="panel panel-default mb0 mt1" id="reply<?=$itemsReply->getId()?>">
                                <div class="panel-heading clearfix">
                                    <em><u><?=date("d.m.Y", strtotime($itemsReply->getTimestamp()));?></u> г.,</em>
                                    <strong><?=$itemsReply->getAuthor();?></strong>
                                    <?php if($this->user->email == $itemsReply->getEmail() || $this->user->role == 'admin'):?>
                                        <div class="btn-group btn-group-sm pull-right"
                                             role="group"
                                             aria-label="..."
                                             id="<?=$itemsReply->getId();?>">
                                            <button type="button" class="btn btn-default reply-forum" data-action="edit">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                            </button>
                                            <button type="button" class="btn btn-default delete-forum" data-action="delete">
                                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                            </button>
                                        </div>
                                        <div class="hidden markdown-content">
                                            <?=($itemsReply->getContentMarkdown() != '')
                                                ?$itemsReply->getContentMarkdown()
                                                :$itemsReply->getContent();?>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="panel-body">
                                    <?=$itemsReply->getContent();?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach;?>

    </div>
    <?= $this->render('components/_paginator.phtml')?>
<?php endif;?>

<div class="modal fade" id="modalForumAdmin" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modalLabel"></h4>
            </div>
            <form action="" id="modalForumForm" name="modalForumForm" method="post">
                <div class="modal-body" id="modalBody"></div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" name="action">Сохранить</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                </div>
                <?php if($this->currentPage):?>
                    <input type="hidden" name="page" value="<?=$this->currentPage?>"/>
                <?php endif;?>
            </form>
        </div>
    </div>
</div>