<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->breadcrumbs = true;
$this->sidebar_headers = true;
?>
<div class="row mb2">
    <div class="col-md-12">
        <?php if($this->category->getImage()):?>
            <div class="col-md-3 pull-right">
                <div class="thumbnail">
                    <img src="<?=$this->category->getImage()?>" alt="<?=$this->category->getTitle()?>">
                </div>
            </div>
        <?php endif;?>
        <?=$this->category->getContentHtml();?>
    </div>
</div>
<div class="container-fluid product-list">
    <?php if($this->listItems): ?>
        <?php foreach ($this->listItems as $item): ?>
            <div class="row product-item">
                <div class="col-md-9">
                    <h2 class="h4 mb2">
                        <a href="<?=
                            ($item->getImageTable())
                                ? $item->getImageTable()
                                : $this->url(
                                    array(
                                        'controller' => 'pipeline',
                                        'action' => 'view',
                                        'fullPath' => $item->getFullPath()
                                    ),'pipeline',true,false
                                )?>" target="<?=$item->getImageTable() && '_blank'?>">
                            <?=$this->escape($item->getTitle());?>
                            <?php if($item->getImageTable()):?>
                                <img src="/images/pdf-file.png" alt="<?=$item->getTitle()?>" class="mlr1"/>
                            <?php endif;?>
                        </a>
                    </h2>
                    <div class="product-property">
                        <?php $properties = $this->getPipelineProperties($item->getId())?>
                        <?php if(!empty($properties)):?>
                            <table class="table table-striped table-condensed product-property">
                            <?php foreach ($properties as $property => $value):?>
                                <tr>
                                    <th class="col-md-4"><?= $property ?></th>
                                    <td><?= $value->getValue() ?></td>
                                </tr>
                            <?php endforeach;?>
                            </table>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    <?php endif;?>
</div>
