<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->meta_description = $this->pipeline->getMetaDescription();
$this->meta_keywords = $this->pipeline->getMetaKeywords();
$this->breadcrumbs = true;
$this->sidebar_headers = true;
?>
<div class="col-xs-6 col-md-3">
    <div class="product-images">
        <div class="thumbnail">
            <img src="<?= ($this->pipeline->getImage())
                ? $this->pipeline->getImage()
                : '/files/images/product/2012-05-22_foto_nv.jpg'; ?>" alt="<?= $this->escape($this->pipeline->getTitle()); ?>">
        </div>
        <?php if($this->pipeline->getImageDraft()):?>
            <div class="thumbnail">
                <a href="" data-toggle="modal" data-target="#draftImagePipeline">
                    <img src="<?=$this->pipeline->getImageDraft();?>" alt="<?=$this->pipeline->getTitle()?>"/>
                </a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="draftImagePipeline" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel"><?=$this->escape($this->pipeline->getTitle())?></h4>
                        </div>
                        <div class="modal-body">
                            <div class="modal-draft-images text-center">
                                <img src="<?=$this->pipeline->getImageDraft();?>" alt="<?=$this->escape($this->pipeline->getTitle());?>"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>

<div class="col-xs-6 col-md-8 col-md-offset-1">
    <?php if($this->properties):?>
        <h4>Свойства</h4>
        <table class="table table-striped table-condensed product-property">
            <?php foreach ($this->properties as $property => $value):?>
                <tr>
                    <th class="col-md-4"><?= $property ?></th>
                    <td><?= $value->getValue() ?></td>
                </tr>
            <?php endforeach;?>
        </table>
    <?php endif;?>

    <?php if($this->pipeline->getImageTable()):?>
        <div class="row mb2">
            <div class="col-xs-4">
                <h4>Стандарты и ГОСТы</h4>
            </div>
            <div class="col-xs-8">
                <a href="<?=$this->pipeline->getImageTable()?>" class="btn btn-info" target="_blank"><span class="fa fa-file-pdf-o"></span></a>
            </div>
        </div>
    <?php endif;?>

    <?php if($this->pipeline->getDescription()):?>
        <div class="mb2">
            <h4>Описание</h4>
            <?=$this->pipeline->getDescription()?>
        </div>
    <?php endif;?>

    <?php if($this->pipeline->getContentHtml()):?>
        <div class="mb2">
            <?=$this->pipeline->getContentHtml()?>
        </div>
    <?php endif;?>

</div>


<?php $this->headScript()
    ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js');?>