<div>
    <form action="" method="get"  class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-2 control-label">Категория</label>
            <div class="col-sm-5">
                <select name="category_id" class="form-control">
                    <?php foreach ($this->categories as $category):?>
                        <option value="<?= $category->getId()?>"><?= $category->getName()?> (<?= $category->getId()?>)</option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="col-sm-5">
                <input type="submit" value="Генерировать" class="btn btn-success">
            </div>
        </div>
    </form>
</div>

<pre>
    <?php print_r($this->array)?>
</pre>