<?php
/**
 * @var $page Manufacture_Model_ManufactureCategories
 */
$this->title = 'Производство';
$this->secondary_text = 'Список категорий';
?>
<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th><span class="glyphicon glyphicon-sort"></span></th>
            <th>Наименование</th>
            <th>Url</th>
            <th>Действия</th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><?=$page->getSorting()?></td>
                <td>
                    <a href="<?=$this->url(array(
                        'module'=>'admin',
                        'controller'=>'manufacture-categories',
                        'action'=>'list',
                        'id'=>$page->getId(),
                    ), null, true)?>">
                        <span class="glyphicon glyphicon-folder-close mlr1"></span>
                        <?=$page->getTitle()?>
                    </a>
                </td>
                <td>
                    <?php if($page->getDeleted() != 1):?>
                        <a href="/manufacture/<?=$page->getPath()?>/" title="Посмотреть на сайте">
                            <?=$page->getPath()?>
                            <span class="glyphicon glyphicon-link mlr1"></span>
                        </a>
                    <?php else:?>
                        <?=$page->getPath()?>
                    <?php endif;?>
                </td>
                <td width="150px">
                    <?=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'manufacture-categories',
                        'item_id' => $page->getId(),
                        'item_path' => '/manufacture/'.$page->getPath(),
                        'active' => ($page->getActive() != 0)? true : false,
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
<?php endif;?>
<div class="pull-left">
    <a href="<?=$this->url(
        array('module'=>'admin', 'controller' => 'manufacture-categories', 'action' => 'add'),
        false,true
    )?>" class="btn btn-default <?=($this->identity->role != 'admin')?'disabled':''?>">Добавить категорию</a>
</div>
<?= $this->render('components/_paginator.phtml')?>
