<?php
$this->title = 'Трубопроводная арматура';
$this->secondary_text = 'Список категорий';
?>


<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Заголовок</th>
        <th>Url</th>
        <th>Сортировка</th>
        <th>Активность</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr>
            <td><?=$page->getId()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getPath()?></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td width="150px">
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'pipeline-categories',
                    'action' => 'edit',
                    'id'=>$page->getId()),
                    'adminEdit', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Редактировать">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="/pipeline/<?=$page->getPath().'/';?>"
                   class="btn btn-default btn-xs"
                   title="Просмотр">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                </a>
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'pipeline-categories',
                    'action' => 'delete',
                    'id'=>$page->getId()),
                    'adminEdit', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Удалить">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?= $this->render('components/_paginator.phtml')?>
<?php else:?>
<div class="text-center">
    <a href="<?=$this->url(
    array('module'=>'admin', 'controller' => 'pipeline-categories', 'action' => 'add'),
    false,true
    )?>" class="btn btn-success">Добавить категорию</a>
</div>
<?php endif;?>

