<?php
$this->title = 'Трубопроводная арматура';
$this->secondary_text = 'Список категорий';
?>


<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Заголовок</th>
        <th>Url</th>
        <th>Сортировка</th>
        <th>Активность</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr class="<?=$this->contextualClassTr($page);?>">
            <td><?=$page->getId()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getPath()?></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'pipeline-categories',
                    'item_id' => $page->getId(),
                    'item_path' => '/pipeline/'.$page->getPath(),
                    'deleted' => ($page->getDeleted() != 0)? true : false,
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?= $this->render('components/_paginator.phtml')?>
<?php else:?>
<div class="text-center">
    <a href="<?=$this->url(
    array('module'=>'admin', 'controller' => 'pipeline-categories', 'action' => 'add'),
    false,true
    )?>" class="btn btn-success">Добавить категорию</a>
</div>
<?php endif;?>

