<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->sidebar_headers = false;
$this->breadcrumbs = true;
?>
<div class="col-md-12">
    <?php if($this->mediaItems):?>
        <?php foreach ($this->mediaItems as $mediaItems):?>
            <div class="media media-item line line-dotted">
                <?php if(!is_null($mediaItems->getThumb())):?>
                    <div class="media-left col-md-3">
                        <div class="thumbnail col-md-10 hover-shadow">
                            <a href="<?=$this->url(array(
                                'module' => 'media',
                                'controller' => 'index',
                                'action' => 'view',
                                'media_path_category' => $this->escape($this->currentCategory->getPath()),
                                'media_path_item' => $this->escape($mediaItems->getPath())
                            ),  'mediaFullPath', false, false)?>/">
                                <img src="<?=$this->escape($mediaItems->getThumb())?>" alt="<?=$this->escape($mediaItems->getName())?>" class="media-object"/>
                            </a>
                        </div>
                    </div>
                <?php endif;?>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="<?=$this->url(array(
                            'module' => 'media',
                            'controller' => 'index',
                            'action' => 'view',
                            'media_path_category' => $this->escape($this->currentCategory->getPath()),
                            'media_path_item' => $this->escape($mediaItems->getPath())
                        ),  'mediaFullPath', false, false)?>/"><?=$this->escape($mediaItems->getName())?></a>

                    </h4>
                    <p class="text-muted"><small><em><?=date("d.m.Y", strtotime($mediaItems->getTimestamp()));?> г.</em></small></p>
                    <?=$mediaItems->getSContent()?>
                </div>
            </div>
        <?php endforeach;?>
        <?= $this->render('components/_paginator.phtml')?>
    <?php endif;?>
</div>