<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->sidebar_headers = false;
?>
<?php if($this->mediaItems):?>
    <?php foreach ($this->mediaItems as $mediaItems):?>
        <div class="media media-item line line-dotted">
            <?php if(!is_null($mediaItems->getThumb())):?>
                <div class="media-left col-md-3">
                    <div class="thumbnail col-md-10 hover-shadow">
                        <a href="<?=$this->escape($mediaItems->getFullPath())?>">
                            <img src="<?=$this->escape($mediaItems->getThumb())?>" alt="<?=$this->escape($mediaItems->getName())?>" class="media-object"/>
                        </a>
                    </div>
                </div>
            <?php endif;?>
            <div class="media-body">
                <h4 class="media-heading"><a href="<?=$this->escape($mediaItems->getFullPath())?>"><?=$this->escape($mediaItems->getName())?></a></h4>
                <?=$mediaItems->getSContent()?>
            </div>
        </div>
    <?php endforeach;?>
    <?= $this->render('_paginator.phtml')?>
<?php endif;?>
