<?php
$this->title = "Вход в админ панель";
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?=$this->form_auth; ?>
        <?php if($this->errMessage || $this->forbiddenResource):?>
        <div class="alert alert-danger text-center" role="alert">
            <p><strong>Ошибка!</strong></p>
            <?php if($this->errMessage):?>
                <?=$this->errMessage;?>
            <?php endif;?>
            <?php if($this->forbiddenResource):?>
                <p>Для доступа к <abbr title="<?=$this->forbiddenResource['controller'].'/'.$this->forbiddenResource['action']?>"><strong>данной странице</strong></abbr> нужно обладать правами администратора.</p>
                <p>Выполните вход под учетной записью администратора.</p>
            <?php endif;?>
        </div>
        <?php endif;?>
    </div>
</div>