<?php echo $this->doctype() ?>
<html lang="ru">
<head>
    <?php
    echo $this->headTitle();

    echo $this->render("components/_meta_head.phtml");

    $this->headLink()
        ->appendStylesheet($this->baseUrl().'/css/global.css')
        ->headLink(array('rel' => 'shortcut icon',
            'type' => "image/x-icon",
            'href' => $this->baseUrl().'/img/favicons/favicon.ico'),
            'PREPEND');
    echo $this->headLink();

    $this->headScript()
        ->prependFile('//code.jquery.com/jquery-1.11.3.min.js');
    ?>
</head>
<body>
<div class="layout">
    <?php echo $this->render("components/_header.phtml")?>
    <div class="main" role="main">
        <div class="container">
            <?= $this->layout()->content ?>
        </div>
    </div>
    <div class="layout-footer"></div>
</div>
<?= $this->render("components/_footer.phtml")?>
<?= $this->headScript();?>
</body>
</html>