<?php
$this->headScript()->appendFile('/js/catalog.min.js');
?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?=$this->escape($this->title)?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3 categories-list">
        <?php if($this->breadcrumbs):?>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->action(
                        "index",
                        "breadcrumbs",
                        "pipeline",
                        array(
                            'page_category' => $this->category,
                            'page_item' => $this->pipeline,
                        )
                    );?>
                </div>
            </div>
        <?php endif; ?>
        <?=$this->layout()->content?>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?if($this->categories):?>
            <?=$this->render('_sidebar.phtml')?>
        <?endif;?>
    </div>
</div>