<div class="page-header row">
    <div class="col-md-10">
        <h2 class="mt1">
            <?=$this->title?>
            <?php
            if($this->secondary_text)
                echo '<small class="mt1">'.$this->secondary_text.'</small>';
            ?>
        </h2>
    </div>
    <div class="col-md-2">
        <?php if($this->editUrlOptions):?>
            <a href="<?=$this->url($this->editUrlOptions, 'adminEdit',true)?>" class="btn btn-primary mt1"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
        <?php endif;?>
    </div>
</div>
<?=$this->layout()->content?>