<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>
<?php echo $this->doctype() ?>
<html lang="ru">
    <head>
        <?php echo $this->headTitle();?>
        <?php
            echo $this->headLink()
                ->appendStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
                ->appendStylesheet('/css/admin.css');

            $this->headScript()
                ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
                ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
                ->appendFile('/js/admin.min.js')
                ->appendFile('/js/adminSlugify.min.js');
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header col-md-2">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url(array('controller'=>'index', 'action'=>'index'));?>">Admin panel</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?=($controller == 'pages')?'active':'';?>"><a href="<?= $this->url(array('controller'=>'pages', 'action'=>'index'));?>">Страницы</a></li>
                        <li class="<?=($controller == 'manufacture')?'active':'';?>"><a href="<?= $this->url(array('controller'=>'manufacture', 'action'=>'index'));?>">Производство</a></li>
                        <li class="<?=($controller == 'oil')?'active':'';?>"><a href="<?= $this->url(array('controller'=>'oil', 'action'=>'index'));?>">Масла</a></li>
                        <li><a href="/utils/">Утилиты</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/">На сайт</a></li>
                        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                            <li><a href="<?= $this->url(array('controller'=>'auth', 'action'=>'logout'));?>">Выход</a></li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="main" role="main">
            <div class="container">
                <?= $this->layout()->content ?>
            </div>
        </div>
        <div class="loading">
            <div class="spinner">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
        <?php echo $this->headScript();?>
    </body>
</html>
