<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>
<?php echo $this->doctype() ?>
<html lang="ru">
    <head>
        <?php echo $this->headTitle();?>
        <?php
            echo $this->headMeta()
                ->prependName('viewport', 'width=device-width, initial-scale=1.0')
                ->prependHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->prependName('keywords', $this->meta_keywords)
                ->prependName('description', $this->meta_description)
                ->prependHttpEquiv('Content-Type', 'text/html; charset=UTF-8');

            echo $this->headLink()
                ->appendStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
                ->appendStylesheet('/css/admin.css');

            $this->headScript()
                ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
                ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js');
//                ->appendFile('/js/adminSlugify.min.js')
//                ->appendFile('/js/admin.min.js');
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header col-md-2">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="/"><img src="/img/logo/alpha-hydro-logo-ru.svg" alt=""></a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <?= $this->navMenu($this->container_nav)->menu()->setUlClass('nav navbar-nav')->render();?>
                    <?php $this->navbarRightMenu();?>
                    <button name="submit" id="saveItemEdit" type="submit" value="Сохранить изменения" form="itemEdit" class="btn btn-default btn-success navbar-btn hidden navbar-right">Сохранить изменения</button>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="main" role="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-2" role="complementary">
                        <nav class="affix side-nav left mw200">
                            <?php $this->sidebarMenu();?>
                        </nav>
                    </div>
                    <div class="col-md-10" role="main">
                        <?= $this->render('_content_admin.phtml') ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="loading">
            <div class="spinner">
                <div class="bounce1"></div>
                <div class="bounce2"></div>
                <div class="bounce3"></div>
            </div>
        </div>
        <?php echo $this->headScript();?>
    </body>
</html>
