<?php
    /**
    * @var $page Oil_Model_Oil
    */
$this->title = 'Масла и очистители';
$this->secondary_text = $this->categoryName.'Список товара';
?>
<?php if(!empty($this->pages)):?>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th><span class="glyphicon glyphicon-sort"></span></th>
        <?php if(!$this->categoryName):?>
            <th>Категория</th>
        <?php endif;?>
        <th>Наименование</th>
        <th>Действия</th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr class="<?=$this->contextualClassTr($page);?>">
            <td><?=$page->getId()?></td>
            <td><?=$page->getSorting()?></td>
            <?php if(!$this->categoryName):?>
                <td>
                    <?=($this->getCategory($page->getCategoryId(),'oil'))
                        ?$this->getCategory($page->getCategoryId(),'oil')->getTitle()
                        :'нет';
                    ?>
                </td>
            <?php endif;?>
            <td>
                <?php if($page->getDeleted() != 1):?>
                    <a href="/oil/<?=$page->getFullPath();?>" title="Посмотреть на сайте">
                        <?=$page->getTitle()?>
                        <span class="glyphicon glyphicon-link mlr1"></span>
                    </a>
                <?php else:?>
                    <?=$page->getTitle()?>
                <?php endif;?>
            </td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'oil',
                    'item_id' => $page->getId(),
                    'active' => ($page->getActive() != 0)? true : false,
                    'deleted' => ($page->getDeleted() != 0)? true : false,
                    'role' => $this->identity->role
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?php endif;?>
<div class="pull-left">
    <a href="<?=$this->url(
        array(
            'module'=>'admin',
            'controller' => 'oil',
            'action' => 'add',
            'id' => $this->category_id
        ),
        false,true
    )?>" class="btn btn-default <?=($this->identity->role != 'admin')?'disabled':''?>">Добавить товар</a>
</div>
<?= $this->render('components/_paginator.phtml')?>