<?php
$this->title = 'Масла';
$this->secondary_text = 'Список товара';
?>
<?php if(!empty($this->pages)):?>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Заголовок</th>
        <th>Url</th>
        <th>Сортировка</th>
        <th>Активность</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr>
            <td><?=$page->getId()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getPath()?></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'oil',
                    'item_id' => $page->getId(),
                    'item_path' => '/oil/'.$page->getPath(),
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?php else:?>
<div class="text-center">
    <a href="<?=$this->url(
        array('module'=>'admin', 'controller' => 'oil', 'action' => 'add'),
        false,true
    )?>" class="btn btn-success">Добавить товар</a>
</div>
<?php endif;?>