<div class="page-header">
    <h1>Масла</h1>
</div>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Заголовок</th>
        <th>Url</th>
        <!--<th>Описание</th>-->
        <th>Активность</th>
        <th>Сортировка</th>
        <th>Архив</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr>
            <td><?=$page->getId()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getPath()?></td>
            <!--<td><?/*=$page->getDescription()*/?></td>-->
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getDeleted()?>" <?=($page->getDeleted() != 0)?'checked':'';?>></td>
            <td width="100px">
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'oil',
                    'action' => 'edit',
                    'id'=>$page->getId()),
                    'adminEdit', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Редактировать">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="/oil/<?=$page->getPath().'/';?>"
                   class="btn btn-default btn-xs"
                   title="Просмотр">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                </a>
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'oil',
                    'action' => 'delete',
                    'id'=>$page->getId()),
                    'adminEdit', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Удалить">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<div class="pull-right">
    <a href="<?=$this->url(
        array('module'=>'admin', 'controller' => 'oil', 'action' => 'add'),
        false,true
    )?>" class="btn btn-success">Добавить</a>
</div>