<?php
$this->headScript()
    ->appendFile('/js/forumAsk.js');
?>
<div class="form-ask" id="formAsk">
    <h3>Написать нам:</h3>
    <form action="/forum/ask/" method="post" id="forum_ask">
        <?=$this->form_ask->active?>
        <?=$this->form_ask->deleted?>
        <div class="form-inline clearfix">
            <div class="pull-left">
                <?=$this->form_ask->author?>
            </div>
            <?=$this->form_ask->email?>
            <div class="pull-right">
                <?=$this->form_ask->category?>
            </div>
        </div>
        <?=$this->form_ask->content?>
        <div class="row">
            <div class="col-md-6">
                <div class="form-inline m0" id="captcha-form">
                    <?=$this->form_ask->captcha?>
                    <button id="refreshCaptcha" type="button" class="btn btn-default"><i class="fa fa-lg fa-refresh"></i></button>
                </div>
            </div>
            <div class="col-md-4">
                <p class="help-block text-danger">* Все поля обязательны для заполнения</p>
            </div>
            <div class="col-md-2">
                <input type="submit" value="Отправить" class="forum-send" id="forum_send_ask"/>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="modalResponseForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="ajaxResponseForm"></div>
    </div>
</div>