<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->sidebar_headers = false;
?>

<?php foreach ($this->categories as $category): ?>
    <div class="col-md-4 text-center">
        <div class="row">
            <div class="col-md-12 col-lg-9">
                <a class="categories-list-item z-depth-1" href="<?=$this->url(
                    array(
                        'fullPath'=>$category->getFullPath()
                    ), 'pipeline',true,false) ?>">
                    <img src="<?=($category->getImage())
                        ?$category->getImage()
                        :'/files/images/product/2012-05-22_foto_nv.jpg';?>"
                         alt="<?=$category->title?>"/>
                    <p class="categories-list-item-name"><?=$category->title?></p>
                </a>
            </div>
        </div>
    </div>
<?php endforeach; ?>
