<?php
$this->headScript()
		->appendFile('/js/classie/classie.min.js')
		->appendFile('/typescript/test.min.js');
?>
<div class="btn-group btn-group-sm mtb2" data-toggle="buttons">
    <button class="btn btn-default no-disabled" data-toggle="modal" data-target="#myModal">Добавить</button>
    <button class="btn btn-default" disabled="disabled" data-toggle="modal" data-target="#myModal">Редактировать</button>
    <button class="btn btn-default" disabled="disabled" data-toggle="modal" data-target="#myModal">Удалить</button>
</div>
<table class="table table-bordered table-hover">
	<thead>
	<tr>
		<th>#</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Username</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<th scope="row">1</th>
		<td>Mark</td>
		<td>Otto</td>
		<td>@mdo</td>
	</tr>
	<tr>
		<th scope="row">2</th>
		<td>Jacob</td>
		<td>Thornton</td>
		<td>@fat</td>
	</tr>
	<tr>
		<th scope="row">3</th>
		<td>Larry</td>
		<td>the Bird</td>
		<td>@twitter</td>
	</tr>
	</tbody>
</table>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->