<?php
$this->headScript()
		->appendFile('/js/classie/classie.min.js')
		->appendFile('/js/adminTableEdit.js');
?>
<div class="btn-group btn-group-sm mtb2" data-toggle="buttons">
    <button class="btn btn-default no-disabled" data-toggle="modal" data-target="#propertyEditModal" data-action="add">Добавить</button>
    <button class="btn btn-default" disabled="disabled" data-toggle="modal" data-target="#propertyEditModal" data-action="edit">Редактировать</button>
    <button class="btn btn-default" disabled="disabled" data-toggle="modal" data-target="#propertyEditModal" data-action="delete">Удалить</button>
</div>
<table class="table table-bordered table-hover" data-edit="modal">
	<thead>
	<tr>
		<th>#</th>
		<th>Свойство</th>
		<th data-name="value">Значение</th>
		<th data-name="sorting">Порядок</th>
	</tr>
	</thead>
	<tbody>
    <?php if($this->properties):?>
        <?php $n = 1;?>
        <?php foreach ($this->properties as $property => $value):?>
            <tr id="<?=$value->getId()?>">
                <th scope="row"><?= $n?></th>
                <td><?= $property ?></td>
                <td><?= $value->getValue()?></td>
                <td><?= $this->getPropertyPipeline($value->getId())->getSorting()?></td>
            </tr>
            <?php $n++;?>
        <?php endforeach;?>
    <?php endif;?>
	</tbody>
</table>
<div class="modal fade" id="propertyEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <form id="pipelinePropertyValue" enctype="multipart/form-data" action="" method="post">
                    <?=$this->formValue->pipelineId?>
                    <?=$this->formValue->propertyId?>
                    <?=$this->formValue->value?>
                    <?=$this->formValue->sorting?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" form="pipelinePropertyValue" class="btn btn-primary">Сохранить</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->