<?php
$this->headScript()
		->appendFile('/js/classie/classie.min.js')
		->appendFile('/js/pipelinePropertyEdit.js')
		->appendFile('/js/adminSlugify.min.js');
?>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-9">
            <table class="table table-hover" data-edit="modal" data-itemId="<?=$this->pipelineId;?>" id="pipelineProperty">
                <thead>
                <tr>
                    <th class="col-xs-2">Свойство</th>
                    <th data-name="value">Значение</th>
                    <!--<th class="col-xs-1" data-name="sorting">Порядок</th>-->
                    <th class="col-xs-3"></th>
                </tr>
                </thead>
                <tbody>
                <?php if($this->properties):?>
                    <?php foreach ($this->properties as $property => $value):?>
                        <tr id="<?=$value->getId()?>">
                            <td><?= $property ?></td>
                            <td><input type="text" value="<?= $value->getValue()?>" class="input-hidden" readonly="readonly"></td>
                            <!--<td><input type="text" value="<?/*= $this->getPropertyPipeline($value->getId())->getSorting()*/?>" class="input-hidden" readonly="readonly"></td>-->
                            <td>
                                <div class="btn-group btn-group-sm mr1">
                                    <button class="btn btn-default" data-event="edit">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button class="btn btn-default" data-event="delete">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </div>
                                <button type="button" class="btn btn-sm btn-success hidden" data-event="save">Сохранить</button>
                            </td>
                        </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
                <tfoot>
                <tr>
                    <form>
                        <td>
                            <?=$this->formValue->propertyId?>
                        </td>
                        <td><?=$this->formValue->value?></td>
                        <!--<td><?/*=$this->formValue->sorting*/?></td>-->
                        <td><button type="button" class="btn btn-sm btn-primary hidden" data-event="add">Добавить</button></td>
                    </form>
                </tr>
                </tfoot>
            </table>
            <?=$this->formValue->pipelineId?>
        </div>
    </div>
</div>
<div class="modal fade" id="propertyNewModal" tabindex="-1" role="dialog" aria-labelledby="newModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Новое свойство</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="newPipelineProperty" name="newProperty">
                    <div class="form-group">
                        <label for="newPropertyName" class="col-sm-4 control-label">Наименование свойства</label>
                        <div class="col-sm-8">
                            <?=$this->formText('newPropertyName', '', array(
                                'placeholder' => 'Наименование свойства',
                                'class' => 'form-control slugify',
                                'data-slugify' => 'newPropertySystemName',
                            ));?>
                            <?=$this->formHidden('newPropertySystemName','');?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="newPropertyValue" class="col-sm-4 control-label">Значение свойства</label>
                        <div class="col-sm-8">
                            <?=$this->formText('newPropertyValue', '', array(
                                'placeholder' => 'Значение свойства',
                                'class' => 'form-control',
                                'readonly' => 'readonly',
                            ))?>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" form="newPipelineProperty" name="formBtnSubmit" class="btn btn-primary" disabled="disabled">Сохранить</button>
            </div>
        </div>
    </div>
</div>
<!--<div class="modal fade" id="propertyEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <form id="pipelinePropertyValue" enctype="multipart/form-data" action="" method="post">
                    <?/*=$this->formValue->pipelineId*/?>
                    <?/*=$this->formValue->propertyId*/?>
                    <?/*=$this->formValue->value*/?>
                    <?/*=$this->formValue->sorting*/?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" form="pipelinePropertyValue" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </div>
</div>-->