<?php
    if(!$this->sidebar_item)
        $this->sidebar_item = $this->entries;
?>
<ul class="list-group sidebar crop-bottom-shadow">
    <?php if($this->current_category):?>
        <li class="list-group-item sidebar-heading">
            <span class="badge"><i class="fa fa-level-up fa-fw"></i></span>
            <a href="<?=($this->parent_category->id != 0)
                ? $this->url(array('fullPath'=>$this->parent_category->fullPath),'categories', true, false)
                :'/catalog/';?>">
                <?=($this->parent_category->id != 0)
                    ?$this->parent_category->name
                    :'Каталог продукции';?>
            </a>
        </li>
    <?php endif;?>
    <?php foreach ($this->sidebar_item as $entry): ?>
        <li class="list-group-item sidebar-item <?=($entry->id != $this->current_category->id)?'':'sidebar-item-current';?>">
            <?php if($entry->id != $this->current_category->id):?>
                <a href="<?=$this->url(array('fullPath'=>$entry->fullPath),'categories', true, false)?>"><?=$entry->name?></a>
                <?php $subCategories = $this->getSubCategories($entry->id); ?>
                <?php if(!empty($subCategories)):?>
                    <ul class="list-group sidebar-submenu">
                        <?php foreach ($subCategories as $subCategory):?>
                            <li class="list-group-item sidebar-submenu-item">
                                <a href="<?=$this->url(array('fullPath'=>$subCategory->fullPath),'categories', true, false)?>"><?=$subCategory->name?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php else: ?>
                <?=$entry->name?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>