<?php
    $this->title = $this->escape($this->page->title);
    $this->headTitle($this->title);
    $this->meta_title = $this->escape($this->page->metaTitle);
    $this->meta_description = $this->escape($this->page->metaDescription);
    $this->meta_keywords = $this->escape($this->page->metaKeywords);
?>
<div class="hidden">
    <h1><?=$this->escape($this->page->title);?></h1>
    <div><?=$this->escape($this->page->description);?></div>
</div>
<div class="sections">
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Каталог продукции</h2>
                <a href="/catalog/">
                    <img src="/images/sections/catalog560x325.png" alt="Каталог продукции" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Наше производство</h2>
                <a href="/manufacture/">
                    <img src="/images/sections/production560x325.png" alt="Наше производство" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Масла</h2>
                <a href="/oil/">
                    <img src="/images/sections/oils560x325.png" alt="Масла" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Трубопроводная арматура</h2>
                <a href="/pipeline/">
                    <img src="/images/sections/pipeline-access560x325.png" alt="Трубопроводная арматура" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?=$this->render('index/_block_news.phtml');?>
    </div>
    <div class="col-md-4">
        <?=$this->render('index/_block_article.phtml');?>
    </div>
    <div class="col-md-4">
        <?=$this->render('index/_block_forum.phtml');?>
    </div>
</div>
