<?php
    $this->title = $this->escape($this->page->title);
    $this->headTitle($this->title);
    $this->meta_title = $this->escape($this->page->metaTitle);
    $this->meta_description = $this->escape($this->page->metaDescription);
    $this->meta_keywords = $this->escape($this->page->metaKeywords);
?>
<div class="sections">
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Каталог продукции</h2>
                <a href="/catalog">
                    <img src="/images/sections/catalog560x325.png" alt="Каталог продукции" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Наше производство</h2>
                <a href="/production">
                    <img src="/images/sections/production560x325.png" alt="Наше производство" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Масла</h2>
                <a href="/oil">
                    <img src="/images/sections/oils560x325.png" alt="Масла" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Трубопроводная арматура</h2>
                <a href="/pipeline">
                    <img src="/images/sections/pipeline-access560x325.png" alt="Трубопроводная арматура" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="home-i-block gradient z-depth-1">
            <div class="block-head">
                <h2 class="pull-left">Новости</h2>
                <a href="" class="btn btn-alpha default pull-right">Все новости</a>
            </div>
            <div class="block-body">
                <div class="media">
                    <h4 class="media-heading"><a href="#" class="title">Перчатки защитные</a></h4>
                    <div class="media-left">
                        <img class="media-object" src="/files/common/20150625_130548gloves.jpg" alt="...">
                    </div>
                    <div class="media-body">
                        <p class="description">Рабочие перчатки из высококачественной мягкой свиной кожи и синтетической ткани.</p>
                    </div>
                </div>
            </div>
            <div class="block-footer">
                <a href="" class="btn btn-link icon-action">Акции >>></a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="home-i-block gradient z-depth-1">
            <div class="block-head">
                <h2 class="pull-left">Статьи</h2>
                <a href="" class="btn btn-alpha default pull-right">Все статьи</a>
            </div>
            <div class="block-body">
                <div class="media">
                    <h4 class="media-heading"><a href="#" class="title">Проблема выбора РВД</a></h4>
                    <div class="media-body">
                        <p class="description">В настоящее время каждый крупный производитель техники и оборудования производит привязку покупателя путем выпуска оригинальных деталей, что создает сложности определения и совместимости шлангов РВД.</p>
                    </div>
                </div>
            </div>
            <div class="block-footer">
                <a href="" class="btn btn-link pull-right">Подробнее >>></a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?=$this->render('index/_block_forum.phtml');?>
    </div>
</div>
