<div class="sections">
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Каталог продукции</h2>
                <a href="/catalog">
                    <img src="/images/sections/catalog560x325.png" alt="" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Наше производство</h2>
                <a href="/production">
                    <img src="/images/sections/production560x325.png" alt="" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Масла</h2>
                <a href="/oil">
                    <img src="/images/sections/oils560x325.png" alt="" class="img-responsive">
                </a>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="section">
                <h2 class="caption">Трубопроводная арматура</h2>
                <a href="/pipeline">
                    <img src="/images/sections/pipeline-access560x325.png" alt="" class="img-responsive">
                </a>
            </div>
        </div>
    </div>
</div>
