<?php
/**
 * @var $page Media_Model_Media
 */

$this->title = 'Пресса';
$this->secondary_text = $this->categoryName.'Список публикаций';

?>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th><span class="glyphicon glyphicon-sort"></span></th>
            <?php if(!$this->categoryName):?>
                <th>Категория</th>
            <?php endif;?>
            <th>Заголовок</th>
            <th>Привязка к разделу сайта</th>
            <th>Действия</th>
        </tr>
        </thead>
        <?php if($this->pages):?>
            <?php foreach ($this->pages as $page):?>
                <tr class="<?=$this->contextualClassTr($page);?>">
                    <td><?=$page->getId()?></td>
                    <td><?=$page->getSorting()?></td>
                    <?php if(!$this->categoryName):?>
                        <td>
                            <?=($this->getCategory($page->getCategoryId(), 'media'))
                                ?$this->getCategory($page->getCategoryId(), 'media')->getName()
                                :'нет';
                            ?>
                        </td>
                    <?php endif;?>
                    <td>
                        <?php if($page->getDeleted() != 1):?>
                            <a href="/media/<?=$page->getFullPath();?>" title="Посмотреть на сайте">
                                <?=$page->getName()?>
                                <span class="glyphicon glyphicon-link mlr1"></span>
                            </a>
                        <?php else:?>
                            <?=$page->getName()?>
                        <?php endif;?>
                    </td>
                    <td>
                        <div class="select-feedback">
                            <?=$this->formSelect('sectionSite_'.$page->getId(),
                                $page->getSectionSiteId(),
                                array(
                                    'class'=>'form-control sectionSite',
                                    'data-itemId' => $page->getId()
                                ),
                                $this->getSectionSite())?>
                            <span class="glyphicon glyphicon-ok select-control-feedback" aria-hidden="true"></span>
                        </div>
                    </td>
                    <td width="150px">
                        <?=$this->partial('_button_group_table.phtml', array(
                            'item_controller' => 'media',
                            'item_id' => $page->getId(),
                            'active' => ($page->getActive() != 0)? true : false,
                            'deleted' => ($page->getDeleted() != 0)? true : false,
                        ))?>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
    </table>
<?= $this->render('components/_paginator.phtml')?>