<?php
    $aHostName = array(
        'alfa-hydro.loc',
        'alfa-hydro.com',
        'www.alfa-hydro.loc',
        'www.alfa-hydro.com',
    );

    $hostHttp = new Zend_Controller_Request_Http();
    $host = $hostHttp->getServer('HTTP_HOST');
    if(!in_array($host, $aHostName))
        $host = 'alpha-hydro.com';

    if($host === 'www.alfa-hydro.com')
        $host = 'alfa-hydro.com';

    //Zend_Debug::dump($hostHttp->getServer())
?>
User-agent: *
Allow: /
Disallow: /captcha*
Disallow: /catalog/categories*
Disallow: /catalog/products*
Disallow: /catalog/basket*
Disallow: /catalog/index*
Disallow: /catalog/*pdf
Disallow: /catalogs*
Disallow: /section*
Disallow: /index*
Disallow: /admin*
Disallow: /storage*
Disallow: /catalogue*
Disallow: /category*
Disallow: /inmobiliaria*
Disallow: /shop_new*
Clean-param: all /forum/
Clean-param: faq /forum/
Clean-param: reviews /forum/

Host: <?=$host?>

Sitemap: http://<?=$host?>/sitemap.xml