<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?=$this->escape($this->title)?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3">
        <?php if($this->breadcrumbs):?>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->action(
                        "index",
                        "breadcrumbs",
                        "oil",
                        array(
                            'page_category' => $this->category,
                            'page_item' => $this->pageItem,
                        )
                    );?>
                </div>
            </div>
        <?php endif; ?>
        <?=$this->layout()->content?>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?php if($this->categories):?>
            <?=$this->render('_sidebar.phtml')?>
        <?php else: ?>
            <?=$this->partial('_sidebar_image.phtml')?>
        <?php endif;?>
        <?=$this->render('/components/_articles.phtml')?>
    </div>
</div>
<?php /*Zend_Debug::dump($this->pageItems)*/?>
