<div class="home-i-block gradient z-depth-1">
    <div class="block-head">
        <h2 class="pull-left">Статьи</h2>
        <a href="/media/article/" class="btn btn-alpha default pull-right">Все статьи</a>
    </div>
    <?php if($this->articleItem):?>
        <div class="block-body">
            <div class="media">
                <h4 class="media-heading">
                    <a href="/media/<?=$this->articleItem->getFullPath()?>/" class="title"><?=$this->articleItem->getName()?></a>
                </h4>
                <div class="media-body">
                    <p class="description"><?=$this->strCrop($this->articleItem->getSContent(), 300)?></p>
                </div>
            </div>
        </div>
        <div class="block-footer">
            <a href="/media/<?=$this->articleItem->getFullPath()?>/" class="btn btn-link pull-right">Подробнее >>></a>
        </div>
    <?php endif;?>
</div>