<div class="btn-group btn-group-sm" role="group">
    <a href="<?=$this->url(array(
        'module' => 'admin',
        'controller' => $this->item_controller,
        'action' => 'edit',
        'id'=>$this->item_id),
        'adminEdit', true, false);?>"
       class="btn btn-default"
       title="Редактировать">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </a>
    <a href="<?=$this->item_path.'/';?>"
       class="btn btn-default"
       title="Просмотр">
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
    </a>
    <a href="<?=$this->url(array(
        'module' => 'admin',
        'controller' => 'pipeline',
        'action' => 'delete',
        'id'=>$this->item_id),
        'adminEdit', true, false);?>"
       class="btn btn-default"
       title="Удалить">
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
    </a>
</div>
