<?php $auth = $this->identity->role;?>
<div class="btn-group btn-group-sm" role="group">
    <a href="<?=$this->url(array(
        'module' => 'admin',
        'controller' => $this->item_controller,
        'action' => 'edit',
        'id'=>$this->item_id),
        'adminEdit', true, false);?>"
       class="btn btn-default"
       title="Редактировать">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </a>
    <?php if(!$this->deleted):?>
        <a href="<?=$this->url(array(
            'module' => 'admin',
            'controller' => $this->item_controller,
            'action' => 'delete',
            'id'=>$this->item_id),
            'adminEdit', true, false);?>"
           class="btn btn-default <?=($auth != 'admin')?'disabled':''?>"
           title="Удалить">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </a>
        <a href="<?=$this->url(array(
            'module' => 'admin',
            'controller' => $this->item_controller,
            'action' => 'enable',
            'id'=>$this->item_id),
            'adminEdit', true, false);?>"
           class="btn btn-<?=($this->active)?'default':'primary'?> <?=($auth != 'admin')?'disabled':''?>"
           title="<?=($this->active)?'скрыть':'показать'?>">
            <span class="glyphicon glyphicon-eye-<?=($this->active)?'close':'open'?>" aria-hidden="true"></span>
        </a>
    <?php else:?>
        <a href="<?=$this->url(array(
            'module' => 'admin',
            'controller' => $this->item_controller,
            'action' => 'delete',
            'id'=>$this->item_id),
            'adminEdit', true, false);?>"
           class="btn btn-default <?=($auth != 'admin')?'disabled':''?>"
           title="Восстановить">
            <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
        </a>
    <?php endif;?>
</div>
