<?php
/**
 * @var $itemsReply Forum_Model_Forum
 * @var $itemQuestion Forum_Model_Forum
 * @var $noReply Forum_Model_Forum
 */
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->sidebar_headers = false;
?>
<?php if($this->no_reply):?>
    <?php foreach ($this->no_reply as $noReply):?>
        <div class="topic">
            <div class="topic-question">
                <div class="topic-title">
                    <strong><?=$noReply->getAuthor();?></strong>
                    <small><em> - <?=date("d.m.Y", strtotime($noReply->getTimestamp()));?> г.</em></small>
                    <small class="pull-right"><?=$noReply->getCategory();?></small>
                </div>
                <div class="topic-content"><?=$noReply->getContent()?></div>
                <?php if($this->auth):?>
                    <div class="forumButtonComponent text-right"
                         data-id="<?=$noReply->getId()?>"
                         data-role="<?=$this->identity->role?>"
                         data-question="true"
                         data-delete="<?=$this->identity->role != 'admin'?>"
                    ></div>
                <?php endif;?>
            </div>
        </div>
    <?php endforeach;?>
    <hr />
<?php endif;?>
<?php if($this->forumItems):?>
    <?php foreach ($this->forumItems as $forumItems):?>
        <?php $itemQuestion = $forumItems['question'];?>
        <div class="topic">
            <div class="topic-question">
                <div class="topic-title">
                    <strong><?=$itemQuestion->getAuthor();?></strong>
                    <small><em> - <?=date("d.m.Y", strtotime($itemQuestion->getTimestamp()));?> г.</em></small>
                    <small class="pull-right"><?=$itemQuestion->getCategory();?></small>
                </div>
                <div class="topic-content"><?=$itemQuestion->getContent()?></div>
                <?php if($this->auth):?>
                    <div class="forumButtonComponent text-right"
                         data-id="<?=$itemQuestion->getId()?>"
                         data-role="<?=$this->identity->role?>"
                         data-question="true"
                         data-delete="<?=$this->identity->role != 'admin'?>"
                    ></div>
                <?php endif;?>
            </div>
            <?php foreach ($forumItems['reply'] as $itemsReply):?>
                <div class="topic-reply">
                    <div class="topic-title">
                        <strong><?=$itemsReply->getAuthor();?></strong>
                        <small><em> - <?=date("d.m.Y", strtotime($itemsReply->getTimestamp()));?> г.</em></small>
                    </div>
                    <div class="topic-content"><?=$itemsReply->getContent()?></div>
                    <?php if($this->auth && ($this->identity->email == $itemsReply->getEmail() || $this->identity->role == 'admin')):?>
                        <div class="forumButtonComponent text-right"
                             data-id="<?=$itemsReply->getId()?>"
                             data-replace="true"
                        ></div>
                    <?php endif;?>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
    <?= $this->render('components/_paginator.phtml')?>
<?php endif;?>
<?php if(!$this->auth) echo $this->render('_form_ask.phtml')?>
