<div class="page-header clearfix">
    <h1 class="col-md-9">Трубопроводная арматура. <small>Свойства товаров.</small></h1>
    <div class="col-md-3 h1">
        <?php if(!empty($this->pages)):?>
            <a href="<?=$this->url(
                array('module'=>'admin', 'controller' => 'pipeline-property', 'action' => 'add'),
                false,true
            )?>" class="btn btn-success pull-right">Добавить Свойство</a>
        <?php endif;?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?php if(!empty($this->pages)):?>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Наименование</th>
                    <th>Системное имя</th>
                    <th>Показывать в списке</th>
                    <th>Сортировка</th>
                    <th>Активность</th>
                    <th></th>
                </tr>
                </thead>
                <?php foreach ($this->pages as $page):?>
                    <tr>
                        <td><?=$page->getId()?></td>
                        <td><?=$page->getName()?></td>
                        <td><?=$page->getSistemName()?></td>
                        <td><input type="checkbox" value="<?=$page->getShowList()?>" <?=($page->getShowList() != 0)?'checked':'';?>></td>
                        <td><?=$page->getSorting()?></td>
                        <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
                        <td width="100px">
                            <a href="<?=$this->url(array(
                                'module' => 'admin',
                                'controller' => 'pipeline-property',
                                'action' => 'edit',
                                'id'=>$page->getId()),
                                'adminEdit', true, false);?>"
                               class="btn btn-default btn-xs"
                               title="Редактировать">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                            <a href="<?=$this->url(array(
                                'module' => 'admin',
                                'controller' => 'pipeline-property',
                                'action' => 'delete',
                                'id'=>$page->getId()),
                                'adminEdit', true, false);?>"
                               class="btn btn-default btn-xs"
                               title="Удалить">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            </table>
            <?= $this->render('components/_paginator.phtml')?>
        <?php else:?>
            <div class="text-center">
                <a href="<?=$this->url(
                    array('module'=>'admin', 'controller' => 'pipeline-property', 'action' => 'add'),
                    false,true
                )?>" class="btn btn-success">Добавить свойство</a>
            </div>
        <?php endif;?>
    </div>
</div>
