<?php
/**
 * @var $page Pipeline_Model_PipelineProperty
 */
$this->title = 'Трубопроводная арматура';
$this->secondary_text = 'Свойства товара';
?>
<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th><span class="glyphicon glyphicon-sort"></span></th>
                <th>Наименование</th>
                <th>Системное имя</th>
                <th>Тип</th>
                <th>Показывать в списке</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><?=$page->getSorting()?></td>
                <td><?=$page->getName()?></td>
                <td><?=$page->getSistemName()?></td>
                <td><?=$this->getTypeText($page->getType())?></td>
                <td><input type="checkbox" value="<?=$page->getShowList()?>" <?=($page->getShowList() != 0)?'checked':'';?>></td>
                <td width="150px">
                    <?=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'pipeline-property',
                        'item_id' => $page->getId(),
                        'active' => ($page->getActive() != 0)? true : false,
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))?>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<?php endif;?>
<div class="pull-left">
    <a href="<?=$this->url(
        array('module'=>'admin', 'controller' => 'pipeline-property', 'action' => 'add'),
        'adminEdit',true
    )?>" class="btn btn-default">Добавить свойство</a>
</div>
<?= $this->render('components/_paginator.phtml')?>
