<?php
$this->title = 'Трубопроводная арматура';
$this->secondary_text = 'Свойства товара';
?>

<div class="row">
    <div class="col-md-12">
        <?php if(!empty($this->pages)):?>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Наименование</th>
                    <th>Системное имя</th>
                    <th>Тип</th>
                    <th>Показывать в списке</th>
                    <th>Сортировка</th>
                    <th>Активность</th>
                    <th></th>
                </tr>
                </thead>
                <?php foreach ($this->pages as $page):?>
                    <tr>
                        <td><?=$page->getId()?></td>
                        <td><?=$page->getName()?></td>
                        <td><?=$page->getSistemName()?></td>
                        <td><?=$this->getTypeText($page->getType())?></td>
                        <td><input type="checkbox" value="<?=$page->getShowList()?>" <?=($page->getShowList() != 0)?'checked':'';?>></td>
                        <td><?=$page->getSorting()?></td>
                        <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
                        <td width="150px">
                            <div class="btn-group btn-group-sm" role="group">
                                <a href="<?=$this->url(array(
                                    'module' => 'admin',
                                    'controller' => 'pipeline-property',
                                    'action' => 'edit',
                                    'id'=>$page->getId()),
                                    'adminEdit', true, false);?>"
                                   class="btn btn-default"
                                   title="Редактировать">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                                <a href="<?=$this->url(array(
                                    'module' => 'admin',
                                    'controller' => 'pipeline-property',
                                    'action' => 'delete',
                                    'id'=>$page->getId()),
                                    'adminEdit', true, false);?>"
                                    class="btn btn-default"
                                    title="Удалить">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach;?>
            </table>
            <?= $this->render('components/_paginator.phtml')?>
            <em class="text-muted">* Удаленные свойства не показываются</em>
        <?php else:?>
            <div class="text-center">
                <a href="<?=$this->url(
                    array('module'=>'admin', 'controller' => 'pipeline-property', 'action' => 'add'),
                    false,true
                )?>" class="btn btn-success">Добавить свойство</a>
            </div>
        <?php endif;?>
    </div>
</div>
