<?php
$this->title = "Редактирование страницы";
?>
<div class="row">
    <div class="col-md-2">
        <nav class="affix">
            <ul class="nav">
                <li><a href="<?=$this->url(array('module'=>'admin', 'controller' => 'pages', 'action' => 'index'), 'adminList', false, true)?>">Список</a></li>
                <li><a href="<?=$this->url(array('module'=>'admin', 'controller' => 'pages', 'action' => 'add'), 'adminAdd', false, true)?>">Новая страница</a></li>
                <li><a href="<?=$this->url(array('module'=>'admin', 'controller' => 'pages', 'action' => 'delete'), 'adminEdit')?>">Удалить</a></li>
            </ul>
        </nav>
    </div>
    <div class="col-md-10">
        <ul class="nav nav-tabs nav-justified"  role="tablist">
            <li role="presentation" class="active"><a href="#fieldset-basic" aria-controls="fieldset-basic" role="tab" data-toggle="tab">Основные</a></li>
            <li role="presentation"><a href="#fieldset-seo" aria-controls="fieldset-seo" role="tab" data-toggle="tab">SEO</a></li>
            <li role="presentation"><a href="#fieldset-additionally" aria-controls="fieldset-additionally" role="tab" data-toggle="tab">Дополнительно</a></li>
        </ul>
        <?=$this->form;?>
    </div>
</div>