<div class="page-header">
    <h1>Статические страницы сайта</h1>
</div>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Url</th>
        <th>Заголовок</th>
        <th>Описание</th>
        <th>Активность</th>
        <th>Сортировка</th>
        <th>Архив</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr>
            <td><?=$page->getId()?></td>
            <td><?=$page->getPath()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getDescription()?></td>
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getDeleted()?>" <?=($page->getDeleted() != 0)?'checked':'';?>></td>
            <td width="100px">
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'pages',
                    'action' => 'edit',
                    'id'=>$page->getId()),
                    'admin', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Редактировать">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="<?=($page->getPath() != 'home')?'/'.$page->getPath().'/':'/';?>"
                   class="btn btn-default btn-xs"
                   title="Просмотр">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                </a>
                <a href="<?=$this->url(array(
                    'module' => 'admin',
                    'controller' => 'pages',
                    'action' => 'delete',
                    'id'=>$page->getId()),
                    'admin', true, false);?>"
                   class="btn btn-default btn-xs"
                   title="Удалить">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
</table>