<?php
/**
 * @var $page Pages_Model_Pages
 */

$this->title = "Разделы сайта";
$this->secondary_text = 'Статические страницы';
?>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th><span class="glyphicon glyphicon-sort"></span></th>
        <th>Наименование</th>
        <th>Url</th>
        <th>Действия</th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr class="<?=$this->contextualClassTr($page);?>">
            <td><?=$page->getId()?></td>
            <td><?=$page->getSorting()?></td>
            <td><?=$page->getTitle()?></td>
            <td>
                <?php if($page->getDeleted() != 1):?>
                    <a href="/<?=($page->getPath() != 'home')?$page->getPath().'/':'';?>" title="Посмотреть на сайте">
                        <?=$page->getPath()?>
                        <span class="glyphicon glyphicon-link mlr1"></span>
                    </a>
                <?php else:?>
                    <?=$page->getPath()?>
                <?php endif;?>
            </td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'pages',
                    'item_id' => $page->getId(),
                    'active' => ($page->getActive() != 0)? true : false,
                    'deleted' => ($page->getDeleted() != 0)? true : false,
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<div class="pull-left">
    <a href="<?=$this->url(
        array('module'=>'admin', 'controller' => 'pages', 'action' => 'add'),
        false,true
    )?>" class="btn btn-default">Добавить раздел</a>
</div>
<?= $this->render('components/_paginator.phtml')?>