<?php
$this->title = "Разделы сайта";
$this->secondary_text = 'Статические страницы';
?>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Заголовок</th>
        <th>Url</th>
        <th>Сортировка в меню</th>
        <th>Активность</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr>
            <td><?=$page->getId()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getPath()?></td>
            <td><?=$page->getSorting()?></td>
            <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'pages',
                    'item_id' => $page->getId(),
                    'item_path' => ($page->getPath() != 'home')?'/'.$page->getPath():'',
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>