<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?=$this->escape($this->title)?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3">
        <?php if($this->breadcrumbs):?>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->action(
                        "index",
                        "breadcrumbs",
                        "media",
                        array(
                            'media_category' => $this->currentCategory,
                            'media_item' => (!$this->mediaItem)
                                ? null
                                :$this->mediaItem,
                        )
                    );?>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <?=$this->layout()->content?>
        </div>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?=$this->render('_sidebar.phtml')?>
    </div>
</div>