<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?=$this->escape($this->title)?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3">
        <?=$this->layout()->content?>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?=$this->render('_sidebar.phtml')?>
    </div>
</div>