<?php
/**
 *@var $category Media_Model_MediaCategories 
 */
$current_category = ($this->currentCategory)?$this->currentCategory->getId():0;
?>
<nav>
    <ul class="list-group sidebar crop-bottom-shadow">
        <?php foreach($this->categories as $category):?>
            <li class="list-group-item sidebar-item <?=($current_category != $category->getId())?'':'sidebar-item-current';?>">
                <?php if($current_category != $category->getId()):?>
                    <a href="<?=$this->url(array(
                        'fullPath' => $category->getPath(),
                    ), 'media', true, false)?>"><?=$this->escape($category->getName())?></a>
                <?php else: ?>
                    <span><?=$this->escape($category->getName())?></span>
                <?php endif; ?>
            </li>
        <?php endforeach;?>
    </ul>
</nav>
