<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="<?=$this->url(array(), 'adminAdvanced', true, false)?>">Advanced Admin</a></li>
                </ul>
            </div>
            <div id="admin-panel" class="col-md-8 text-center"></div>
            <div class="col-md-2">
                <?php $this->navbarRightMenu();?>
            </div>
        </div>
    </div>
</nav>