<?php
    $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
    $dataItem = Zend_Controller_Front::getInstance()->getRequest()->getParam('dataItem');
?>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="/admin/<?=$this->adminPath?>">Advanced Admin</a></li>
                </ul>
            </div>
            <div class="col-md-4 text-center">
                <?php if($action != 'articles'):?>
                    <div
                        id="admin-panel"
                        data-controller="<?=$dataItem['controller']?>"
                        data-id="<?=$dataItem['id']?>"
                        data-active="<?=($dataItem['active'] != 0)?true:false?>"
                        data-deleted="<?=($dataItem['deleted'] != 0)?true:false?>"
                    ></div>
                <?php endif;?>
            </div>
            <div class="col-md-4">
                <?php $this->navbarRightMenu();?>
            </div>
        </div>
    </div>
</nav>