<?php
$this->headScript()
    ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->appendFile("/js/adminAuth.min.js");

$requestParams = Zend_Controller_Front::getInstance()->getRequest()->getParams();

?>
<?php if(!Zend_Auth::getInstance()->hasIdentity()):?>
<div class="modal fade" tabindex="-1" role="dialog" id="modalAuth">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="h4 modal-title">Вход в административную часть</div>
            </div>
            <div class="modal-body">
                <form id="adminAuth" enctype="application/x-www-form-urlencoded" class="form-horizontal" action="/admin/auth/" method="post">
                    <div class=" form-group ">
                        <label for="username" class="col-md-2 control-label optional">Login</label>
                        <div class="col-md-10">
                            <div class="input-group">
                                <span class="input-group-addon">@</span>
                                <input name="username" id="username" value="" placeholder="E-mail" prepend="@" class="form-control" type="text">
                            </div>
                        </div>
                    </div>
                    <div class=" form-group">
                        <label for="password" class="col-md-2 control-label optional">Password</label>
                        <div class="col-md-10">
                            <div class="input-group">
                                <span class="input-group-addon">&#128274;</span>
                                <input name="password" id="password" value="" placeholder="Password" prepend="&amp;#128274;" class="form-control" type="password">
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="adminPath" value="<?=$this->adminPath?>"/>
                </form>
            </div>
            <div class="modal-footer">
                <button form="adminAuth" name="submit" id="submit" type="submit" class="btn btn-default btn-success">Вход</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php endif;?>
<?php $this->headScript()->captureStart() ?>
var goAdmin = new AdminAuth('<?=$this->adminPath?>');
<?php $this->headScript()->captureEnd() ?>
