<?php
$this->pageArticles = $this->getPageArticles();
?>

<?php if(!empty($this->pageArticles)):?>
    <?php foreach ($this->pageArticles as $pageArticle):?>
        <div class="media media-item line line-dotted">
            <?php if($pageArticle->getImage() && $pageArticle->getImage() != ''):?>
                <div class="media-left col-md-2">
                    <div class="thumbnail col-md-10 hover-shadow">
                        <a href="<?=$this->url(array(
                            'path' => $this->escape($pageArticle->getPath())
                        ),  $this->moduleName.'_articles', false, false)?>">
                            <img src="<?=$this->escape($pageArticle->getImage())?>" alt="<?=$this->escape($pageArticle->getName())?>" class="media-object"/>
                        </a>
                    </div>
                </div>
            <?php endif;?>
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="<?=$this->url(array(
                        'path' => $this->escape($pageArticle->getPath())
                    ),  $this->moduleName.'_articles', false, false)?>"><?=$this->escape($pageArticle->getName())?></a>
                </h4>
                <?=$pageArticle->getSContent()?>
                <div class="text-right mt1"><a href="<?=$this->url(array(
                        'path' => $this->escape($pageArticle->getPath())
                    ),  $this->moduleName.'_articles', false, false)?>">читать...</a></div>
            </div>
        </div>
    <?php endforeach;?>
    <?= $this->render('components/_paginator.phtml')?>
<?php endif;?>