<?php
$hostHttp = new Zend_Controller_Request_Http();
$host = $hostHttp->getServer('HTTP_HOST');
?>
<div class="footer" role="contentinfo">
    <div class="wrapper text-center">
        <div>© Альфа-Гидро, 2009-<?=date('Y')?></div>
        <div>Гидравлические системы и компоненты</div>
    </div>
    <div class="admin">
        <div><a href="http://admin.<?=$host?>" class="btn btn-alpha default">Вход</a></div>
    </div>
</div>