<div class="header" role="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-4"><a href="/" class="logo png"></a></div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                <div class="contacts">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-1 hidden-sm hidden-xs">
                            <div class="adress">193312, г. Санкт-Петербург ул.Кржижановского, д.12/1</div>
                        </div>
                        <div class="col-md-3 hidden-sm hidden-xs">
                            <div class="worktime">9:00 - 18:00</div>
                        </div>
                        <div class="col-md-4 col-sm-12 col-xs-12 text-right">
                            <div class="phone">+ 7 (812) <span class="text-size-large">44-949-44</span></div>
                            <div class="text-size-small"><a href="mailto:info@alpha-hydro.com"><i class="fa fa-envelope"></i>  info@alpha-hydro.com</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="main-menu container-fluid">
                    <?php echo $this->partial("components/_main_menu.phtml")?>
                    <?php echo $this->partial("components/_search_form.phtml")?>
                </div>
            </div>
        </div>
    </div>
</div>
