<?php if($this->countPage && $this->countPage > 1):?>
<nav class="text-right">
    <ul class="pagination pagination-sm">
        <li <?=($this->currentPage == 1)?'class="disabled"':''?>>
            <a href="<?=$this->url()?>/<?=($this->currentPage != 1)?'?page='.($this->currentPage-1):'';?>" aria-label="Previous">
                <span aria-hidden="true">«</span>
            </a>
        </li>
        <?php
            for ($i = 1; $i <= $this->countPage; $i++) {
                $href = ($i != 1)
                    ? $this->url().'/?page='.$i
                    : $this->url().'/';
                $item = '<li><a href="'.$href.'">'.$i.'</a></li>';

                if($i == $this->currentPage)
                    $item = '<li class="active"><a href="'.$href.'">'.$i.' <span class="sr-only">(current)</span></a></li>';

                echo $item;
            }
        ?>
        <li <?=($this->currentPage == $this->countPage)?'class="disabled"':''?>>
            <a href="<?=$this->url()?>/?page=<?=($this->currentPage != $this->countPage)?$this->currentPage+1:$this->countPage?>" aria-label="Next">
                <span aria-hidden="true">»</span>
            </a>
        </li>
    </ul>
</nav>
<?php endif;?>