<?php $this->headScript()->appendFile('/js/search.js'); ?>
<form id="search" action="/search/" method="get" class="">
    <div class="dropdown">
        <input
            type="text"
            name="query"
            autocomplete="off"
            value=""
            class="col-md-9"
            placeholder="Поиск"
            id="search-query"/>
        <ul id="search-autocomplete" class="dropdown-menu search-autocomplete col-md-8"></ul>
    </div>
    <!--<input type="submit" value="Поиск" class="col-md-3 col-md-offset-1"/>-->
    <!--<input type="submit" value="Поиск" class="col-md-2 col-md-offset-1 fa fa-search"/>-->
    <button type="submit" class="col-md-2 col-md-offset-1"><i class="fa fa-search fa-lg"></i></button>
</form>
