<?php echo $this->doctype() ?>
<html lang="ru">
<head>
    <meta charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <?php
        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headLink()->appendStylesheet('/public/css/global.css');
    ?>
</head>
<body>
<div class="layout">
    <?php echo $this->partial("components/_header.phtml")?>
    <div class="main" role="main">
        <div class="container">
            <?php echo $this->layout()->content ?>
        </div>
    </div>
    <div class="layout-footer"></div>
</div>
<?php echo $this->partial("components/_footer.phtml")?>
<?php echo $this->headScript();?>
</body>
</html>