<?php
/**
 * @var $this Zend_View_Abstract
 */
echo $this->doctype()
?>
<html lang="ru">
<head>
    <?php
    echo $this->headTitle();

    echo $this->render("components/_meta_head.phtml");

    $this->headLink()
        ->appendStylesheet($this->baseUrl().'/css/global.min.css')
        ->headLink(array('rel' => 'shortcut icon',
            'type' => "image/x-icon",
            'href' => $this->baseUrl().'/favicon.ico'),
            'PREPEND');
    echo $this->headLink();

    $this->headScript()
        ->prependFile('//code.jquery.com/jquery-1.11.3.min.js');
    ?>
</head>
<body>
<div class="layout">
    <?= $this->render("components/admin/_admin_top_panel.phtml")?>
    <?/*= $this->render("components/_header.phtml")*/?>
    <div class="main mt3" role="main">
        <div class="container">
            <?php /*echo $this->layout()->content */?>
            <?= $this->render('_module_admin.phtml') ?>
        </div>
    </div>
    <div class="layout-footer"></div>
</div>
<?= $this->render("components/_admin_auth.phtml");?>
<?= $this->headScript();?>

</body>
</html>