<?php echo $this->doctype() ?>
<html lang="ru">
<head>
    <?php
        echo $this->headTitle();

        echo $this->partial("components/_meta_head.phtml",
            array(
                'meta_title' => $this->meta_title,
                'meta_description' => $this->meta_description,
                'meta_keywords' => $this->meta_keywords
            ));

        $this->headLink()
            ->appendStylesheet($this->baseUrl().'/css/global.css')
            ->headLink(array('rel' => 'shortcut icon',
                'type' => "image/x-icon",
                'href' => $this->baseUrl().'/img/favicons/favicon.ico'),
                'PREPEND');
        echo $this->headLink();

        $this->headScript()
            ->prependFile('//code.jquery.com/jquery-1.11.3.min.js');
    ?>
</head>
<body>
<div class="layout">
    <?php echo $this->partial("components/_header.phtml")?>
    <div class="main" role="main">
        <div class="container">
            <?php echo $this->layout()->content ?>
        </div>
    </div>
    <div class="layout-footer"></div>
</div>
<?php echo $this->partial("components/_footer.phtml")?>
<?php echo $this->headScript();?>
</body>
</html>