<?php
/**
 * @var $this Zend_View_Abstract
 */
echo $this->doctype()
?>
<html lang="ru">
<head>
    <?php
    echo $this->headTitle();

    echo $this->render("components/_meta_head.phtml");

    $this->headLink()
        ->appendStylesheet($this->baseUrl().'/css/global.min.css')
        ->appendStylesheet($this->baseUrl().'/css/admin.min.css')
        ->headLink(array('rel' => 'shortcut icon',
            'type' => "image/x-icon",
            'href' => $this->baseUrl().'/favicon.ico'),
            'PREPEND');
    echo $this->headLink();

    $this->headScript()
        ->prependFile('//code.jquery.com/jquery-1.11.3.min.js')
        ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
        ->appendFile('/js/admin.min.js');
    ?>
</head>
<body>
    <?= $this->render("components/admin/_admin_top_panel.phtml")?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-11">
                <div class="container mb4">
                    <?= $this->render('_module_admin.phtml') ?>
                </div>
            </div>
            <div class="col-md-1">
                <div id="admin-panel"></div>
            </div>
        </div>
    </div>
    <div id="modal" class="my-div"></div>
    <div id="pageData"></div>
    <?/*= $this->render("components/_admin_auth.phtml");*/?>
    <?= $this->headScript();?>
<?php /*Zend_Debug::dump($this->paramsPage());*/?>

</body>
</html>