<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1 <?php if($this->secondaryHeader) echo 'class = "h3 secondary-header"'?>>
                <?=$this->title;?>
                <?php if($this->secondaryHeader):?>
                    <small><?=$this->secondaryHeader;?></small>
                <?php endif;?>
            </h1>
        </div>
    </div>
</div>