<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <?php if($this->secondaryHeader):?>
                <h1 class = "h3 secondary-header"><?=$this->title;?>
                    <small><?=$this->secondaryHeader;?></small>
                </h1>
                <div class="pull-right">
                    <a href="<?= $this->url(array('fullPath' => $this->product->fullPath), 'printPdf', true, false) ?>">Печать</a>
                </div>
            <?php else: ?>
                <h1><?=$this->title;?></h1>
            <?php endif;?>
        </div>
    </div>
</div>