<?php
$this->title = $this->escape($this->page->title);
$this->meta_title = $this->escape($this->page->metaTitle);
$this->headTitle($this->meta_title);
$this->meta_description = $this->escape($this->page->metaDescription);
$this->meta_keywords = $this->escape($this->page->metaKeywords);

$this->headLink()
    ->appendStylesheet($this->baseUrl().'/css/magnific-popup.css');

$this->headScript()
    ->appendFile('/js/magnific/jquery.magnific-popup.min.js')
    ->appendFile('/js/magnific.min.js');
?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?= $this->escape($this->title); ?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3">
        <?=$this->page->contentHtml?>
        <div class="popup-gallery">
            <div class="col-md-4 item">
                <a href="/files/images/about/IMG_5130s.jpg" class="thumbnail"><img src="/files/images/about/thumbs/IMG_5130s_thumb.jpg" alt=""></a>
            </div>
            <div class="col-md-4 item">
                <a href="/files/images/about/IMG_5140s2.jpg" class="thumbnail"><img src="/files/images/about/thumbs/IMG_5140s2_thumb.jpg" alt=""></a>
            </div>
            <div class="col-md-4 item">
                <a href="/files/images/about/IMG_5145as.jpg" class="thumbnail"><img src="/files/images/about/thumbs/IMG_5145as_thumb.jpg" alt=""></a>
            </div>
            <div class="col-md-4 col-md-offset-2 item">
                <a href="/files/images/about/IMG_5164s.jpg" class="thumbnail"><img src="/files/images/about/thumbs/IMG_5164s_thumb.jpg" alt=""></a>
            </div>
            <div class="col-md-4 item">
                <a href="/files/images/about/IMG_5170s.jpg" class="thumbnail"><img src="/files/images/about/thumbs/IMG_5170s_thumb.jpg" alt=""></a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?=$this->partial('components/_sidebar_contact_info.phtml')?>
    </div>
</div>