<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->breadcrumbs = true;
$this->sidebar_headers = true;
?>

<?php foreach ($this->entries as $entry): ?>
    <div class="col-md-3 text-center ">
        <a class="categories-list-item z-depth-1" href="<?=$this->url(
            array(
                'controller' => 'products',
                'action'=>'view',
                'fullPath'=>$entry->fullPath
            ),'catalog',true,false) ?>">
            <img src="/files/images/category/<?=$entry->image;?>" alt="<?=$entry->sku?>"/>
            <p class="categories-list-item-name"><?=$entry->sku?></p>
        </a>
    </div>
<?php endforeach; ?>
