<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->breadcrumbs = true;
$this->sidebar_headers = true;
?>

<div class="container-fluid product-list">
    <?php foreach ($this->entries as $entry): ?>
        <div class="row product-item">
            <div class="col-md-3">
                <div class="thumbnail product-images">
                    <a href="<?=$this->url(
                        array(
                            'controller' => 'products',
                            'action'=>'view',
                            'fullPath'=>$entry->fullPath
                        ),'catalog',true,false) ?>">
                        <img src="/files/images/category/<?=$entry->image;?>" alt="<?=$entry->name?>"/>
                    </a>
                </div>
            </div>
            <div class="col-md-9">
                <h2 class="h4">
                    <a href="<?=$this->url(
                        array(
                            'controller' => 'products',
                            'action'=>'view',
                            'fullPath'=>$entry->fullPath
                        ),'catalog',true,false) ?>">
                        <?=$entry->sku?>
                    </a>
                    <small><?=$entry->name?></small>
                </h2>
                <div class="product-property">
                    <?php $productProperty = $this->getProductProperty($entry->id)?>
                    <?php if(!empty($productProperty)):?>
                    <table class="table table-striped table-condensed product-property">
                        <?php foreach ($productProperty as $property):?>
                            <tr>
                                <th class="col-md-4"><?= $property->name ?></th>
                                <td><?= $property->value ?></td>
                            </tr>
                        <?php endforeach;?>
                    </table>
                    <?php endif;?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
