<?php
$this->headTitle($this->title .'. '. $this->secondaryHeader);
$this->meta_title = $this->title .'. '. $this->secondaryHeader;
$this->breadcrumbs = true;
$this->sidebar_headers = true;
$this->product_id = $this->product->id;
?>

<div class="col-xs-6 col-md-3">
    <div class="product-images">
        <div class="thumbnail">
            <img src="/files/images/product/<?=$this->product->image;?>" alt="<?=$this->product->name?>"/>
        </div>
        <?php if($this->draftImage):?>
            <div class="thumbnail">
                <a href="#" data-toggle="modal" data-target="#draftImageProduct">
                    <img src="/files/images/product/<?=$this->draftImage;?>" alt="<?=$this->product->name?>"/>
                </a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="draftImageProduct" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel"><?=$this->product->sku?> <small><?=$this->product->name?></small></h4>
                        </div>
                        <div class="modal-body">
                            <div class="modal-draft-images text-center">
                                <img src="/files/images/product/<?=$this->draftImage;?>" alt="<?=$this->product->name?>"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>
<div class="col-xs-6 col-md-9">
    <?php if($this->productProperty):?>
        <h4>Свойства</h4>
        <table class="table table-striped table-condensed product-property">
            <?php foreach ($this->productProperty as $property):?>
                <tr>
                    <th class="col-md-4"><?= $property->name ?></th>
                    <td><?= $property->value ?></td>
                </tr>
            <?php endforeach;?>
        </table>
    <?php endif;?>
</div>

<div class="col-md-12">
    <div class="footnote">
        <?php if($this->product->description != ''):?>
            <h4>Примечание</h4>
            <?=$this->product->description?>
        <?php endif;?>
    </div>
</div>
<?php if($this->modifications):?>
    <div class="col-md-12">
        <!--<h4>Модификации и размеры</h4>-->
        <table class="table table-striped modifications">
            <thead>
            <tr>
                <td>Название</td>
                <?php if($this->subproductProperty):?>
                    <?php foreach ($this->subproductProperty as $propertyName):?>
                        <td><?=$propertyName->name?></td>
                    <?php endforeach;?>
                <?php endif;?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->modificationsTableValues as $modification):?>
                <tr>
                    <?php foreach ($modification as $value):?>
                        <td><?=$value ?></td>
                    <?php endforeach;?>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php endif;?>

<?php $this->headScript()
    ->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js');?>