<?php
$this->headTitle($this->title .'. '. $this->secondaryHeader);
$this->meta_title = $this->title .'. '. $this->secondaryHeader;
$this->breadcrumbs = true;
$this->sidebar_headers = true;

/**
 * @var $product Catalog_Model_Products
 * @var $property Catalog_Model_ProductParams
 * @var $subproductProperty Catalog_Model_SubproductParams
 */
$product = $this->product;
$this->product_id = $product->getId();

?>

<div class="col-xs-6 col-md-3">
    <div class="product-images">
        <div class="thumbnail">
            <img src="<?=$product->getUploadPath() . $product->getImage();?>" alt="<?=$product->getName()?>"/>
        </div>
        <?php if($this->draftImage):?>
            <div class="thumbnail">
                <a href="#" data-toggle="modal" data-target="#draftImageProduct">
                    <img src="<?=$product->getUploadPathDraft() . $product->getDraft()?>" alt="<?=$product->getName()?>"/>
                </a>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="draftImageProduct" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel"><?=$this->transformProductSku($product->getSku())?> <small><?=$product->getName()?></small></h4>
                        </div>
                        <div class="modal-body">
                            <div class="modal-draft-images text-center">
                                <img src="<?=$product->getUploadPathDraft() . $product->getDraft()?>" alt="<?=$product->getName()?>"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>
<div class="col-xs-6 col-md-9">
    <?php if($this->productProperty):?>
        <div class="row">
            <div class="col-xs-11"><h4>Свойства</h4></div>
            <div class="col-xs-1" id="product-property-edit" data-id="<?=$product->getId()?>"  role="<?=$this->identity->role?>"></div>
        </div>
        <table class="table table-striped table-condensed product-property">
            <?php foreach ($this->productProperty as $property):?>
                <tr>
                    <th class="col-md-4"><?= $property->getName() ?></th>
                    <td><?= $property->getValue() ?></td>
                </tr>
            <?php endforeach;?>
        </table>
    <?php endif;?>

    <?php if($product->getDescription() != ''):?>
        <div class="row mb2">
            <div class="col-md-12">
                <h4>Описание</h4>
                <?=$product->getDescription()?>
            </div>
        </div>
    <?php endif;?>
</div>


<?php if($this->modifications):?>
    <div class="col-md-12">
        <div class="row">
            <div class="col-xs-10"><h4>Модификации и размеры</h4></div>
            <div class="col-xs-2" id="product-modification-edit" data-id="<?=$product->getId()?>" role="<?=$this->identity->role?>"></div>
        </div>
        <table class="table table-striped modifications">
            <thead>
            <tr>
                <td>Название</td>
                <?php if($this->subproductProperty):?>
                    <?php foreach ($this->subproductProperty as $subproductProperty):?>
                        <td><?=$subproductProperty->getName()?></td>
                    <?php endforeach;?>
                <?php endif;?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->modificationsTableValues as $modification):?>
                <tr>
                    <?php foreach ($modification as $value):?>
                        <td><?=$value ?></td>
                    <?php endforeach;?>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php endif;?>

<div class="col-md-12">
    <div class="footnote">
        <?php if($product->getNote() != ''):?>
            * <?=$product->getNote()?>
        <?php endif;?>
    </div>
</div>