<?php
/* @var $page Oil_Model_OilCategories */

$this->title = 'Масла и очистители';
$this->secondary_text = 'Список категорий';
?>

<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Заголовок</th>
            <th>Url</th>
            <th>Сортировка</th>
            <th>Активность</th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><a href="<?=$this->url(array(
                        'module'=>'admin',
                        'controller'=>'oil-categories',
                        'action'=>'list',
                        'id'=>$page->getId(),
                    ), null, true)?>"><?=$page->getTitle()?></a></td>
                <td><?=$page->getPath()?></td>
                <td><?=$page->getSorting()?></td>
                <td>
                    <a href="<?= $this->url(array(
                        'module' => 'admin',
                        'controller' => 'oil-categories',
                        'action' => 'enable',
                        'id'=>$page->getId()
                    ), 'adminEdit', true, false); ?>" title="<?=($page->getActive() != 0)?'скрыть':'показать'?>">
                        <span class="glyphicon <?=($page->getActive() != 0)?'glyphicon-eye-open':'glyphicon-eye-close'?>"></span>
                    </a>
                </td>
                <td width="150px">
                    <?=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'oil-categories',
                        'item_id' => $page->getId(),
                        'item_path' => '/oil/'.$page->getPath(),
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <?= $this->render('components/_paginator.phtml')?>
<?php else:?>
    <div class="text-center">
        <a href="<?=$this->url(
            array('module'=>'admin', 'controller' => 'oil-categories', 'action' => 'add'),
            false,true
        )?>" class="btn btn-success">Добавить категорию</a>
    </div>
<?php endif;?>