<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header col-md-2">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo svg admin" href="/"></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <?/*= $this->navMenu($this->container_nav)->menu()->setUlClass('nav navbar-nav')->render();*/?>
            <?php $this->navbarMainMenu();?>
            <?php $this->navbarRightMenu();?>
            <button name="submit" id="saveItemEdit" type="submit" value="Сохранить изменения" form="itemEdit" class="btn btn-default btn-success navbar-btn hidden navbar-right">Сохранить изменения</button>
        </div><!--/.nav-collapse -->
    </div>
</nav>