<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
$this->breadcrumbs = true;
$this->sidebar_headers = true;
?>

<?php foreach ($this->entries as $entry): ?>
    <div class="col-md-3 text-center ">
        <a class="categories-list-item z-depth-1" href="<?=$this->url(
            array(
                'module' => 'catalog',
                'controller' => 'categories',
                'action' => 'index',
                'fullPath'=>$entry->fullPath,
            ),'catalog',true,false) ?>">
            <img src="<?=$entry->uploadPath.$entry->image;?>" alt="<?=$entry->name?>"/>
            <p class="categories-list-item-name"><?=$entry->name?></p>
        </a>
    </div>
<?php endforeach; ?>