<?php
/**
 * @var $page Catalog_Model_Categories
 */

$this->title = 'Каталог';
$this->secondary_text = 'Список категорий';

?>
<?php if($this->breadcrumbs)
    echo $this->navigation($this->breadcrumbs)->menu()->setUlClass('breadcrumb')?>
<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th><span class="glyphicon glyphicon-sort"></span></th>
            <th>Наименование</th>
            <th>Url</th>
            <th>Действия</th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><?=$page->getSorting()?></td>
                <td>
                    <a href="<?=$this->url(array(
                        'parent_id'=>$page->getId(),
                    ), 'adminCategoriesEdit', true, false)?>">
                        <span class="glyphicon glyphicon-folder-close mlr1"></span>
                        <?=$this->escape($page->getName())?>
                    </a>
                </td>
                <td>
                    <?php if($page->getDeleted() != 1):?>
                    <a href="<?= $this->url(array(
                        'module' => 'catalog',
                        'controller' => 'categories',
                        'action' => 'index',
                        'fullPath'=>$page->getFullPath()
                    ), 'catalog', true, false); ?>" title="Посмотреть на сайте">
                        <?=$page->getFullPath()?>
                        <span class="glyphicon glyphicon-link mlr1"></span>
                    </a>
                    <?php else:?>
                        <?=$page->getFullPath()?>
                    <?php endif;?>
                </td>
                <td width="150px">
                    <div class="itemButtonsComponent"
                         data-id="<?=$page->getId()?>"
                         data-controller="categories"
                         data-active="<?=($page->getActive() != 0)?true:false?>"
                         data-deleted="<?=($page->getDeleted() != 0)?true:false?>"
                         data-role="<?=$this->identity->role?>"
                    ></div>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
<?php endif;?>

<div id="categoriesAddButtton"
     class="pull-left"
     data-id="<?=$this->current_category?>"
     data-controller = "categories"
     data-action="add"
     data-title="Добавить категорию"
></div>

<?= $this->render('components/_paginator.phtml')?>
