<?php
/**
 * @var $page Catalog_Model_Categories
 */

$this->title = 'Каталог';
$this->secondary_text = 'Список категорий';

?>
<?php if($this->breadcrumbs)
    echo $this->navigation($this->breadcrumbs)->menu()->setUlClass('breadcrumb')?>
<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th class="col-md-1">№№ пп</th>
            <th>ID</th>
            <th>Наименование</th>
            <th>Url</th>
            <th>Действия</th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getSorting()?></td>
                <td><?=$page->getId()?></td>
                <td>
                    <a href="<?=$this->url(array(
                        'parent_id'=>$page->getId(),
                    ), 'adminCategoriesEdit', true, false)?>">
                        <span class="glyphicon glyphicon-folder-close mlr1"></span>
                        <?=$page->getName()?>
                    </a>
                </td>
                <td>
                    <?php if($page->getDeleted() != 1):?>
                    <a href="<?= $this->url(array(
                        'module' => 'catalog',
                        'controller' => 'categories',
                        'action' => 'index',
                        'fullPath'=>$page->getFullPath()
                    ), 'catalog', true, false); ?>" title="Посмотреть на сайте">
                        <?=$page->getFullPath()?>
                        <span class="glyphicon glyphicon-link mlr1"></span>
                    </a>
                    <?php else:?>
                        <?=$page->getFullPath()?>
                    <?php endif;?>
                </td>
                <td width="150px">
                    <div class="itemButtonsComponent"
                         data-id="<?=$page->getId()?>"
                         data-controller="categories"
                         data-active="<?=($page->getActive() != 0)?true:false?>"
                         data-deleted="<?=($page->getDeleted() != 0)?true:false?>"
                    ></div>
                    <?/*=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'categories',
                        'item_id' => $page->getId(),
                        'item_path' => '/catalog/'.$page->getFullPath(),
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))*/?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <?= $this->render('components/_paginator.phtml')?>
<?php else:?>
    <div class="text-center">
        <a href="<?=$this->url(
            array('module'=>'admin', 'controller' => 'media-categories', 'action' => 'add'),
            false,true
        )?>" class="btn btn-success">Добавить категорию</a>
    </div>
<?php endif;?>