<?php
    $this->title = $this->escape($this->page->getTitle());
    $this->headTitle($this->title);
    $this->sidebar_headers = false;
    $this->breadcrumbs = false;
?>
<div class="page-content">
    <?php if(!is_null($this->page->getImage())):?>
        <img src="<?= $this->page->getImage() ?>" alt="<?=$this->page->getTitle()?>" class="pull-right"/>
    <?php endif;?>
    <?=$this->page->getContentHtml();?>
</div>
<div class="col-md-12">
    <?php if($this->pageItems):?>
        <?php foreach ($this->pageItems as $pageItems):?>
            <div class="media media-item line line-dotted">
                <?php if(!is_null($pageItems->getImage())):?>
                    <div class="media-left col-md-3">
                        <div class="thumbnail col-md-10 hover-shadow">
                            <a href="<?=$this->url(array(
                                'fullPath' => $pageItems->getPath()
                            ),  'oil', true, false)?>">
                                <img src="<?=$this->escape($pageItems->getImage())?>" alt="<?=$this->escape($pageItems->getTitle())?>" class="media-object"/>
                            </a>
                        </div>
                    </div>
                <?php endif;?>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="<?=$this->url(array(
                            'fullPath' => $pageItems->getPath()
                        ),  'oil', true, false)?>"><?=$this->escape($pageItems->getTitle())?></a>

                    </h4>
                    <p class="text-muted"><small><em><?=date("d.m.Y", strtotime($pageItems->getDateCreate()));?> г.</em></small></p>
                    <?=$pageItems->getDescription()?>
                </div>
            </div>
        <?php endforeach;?>
        <?= $this->render('components/_paginator.phtml')?>
    <?php endif;?>
</div>
