<?php
$this->title = "Новый товар";
?>
<div class="row">
    <div class="col-md-2">
        <div class="clearfix">
            <nav class="affix">
                <ul class="nav">
                    <li><a href="<?=$this->url(
                            array(
                                'fullPath'=>$this->item->getFullPath()
                            ), 'pipeline',true,false
                        )?>" target="_blank"><span class="glyphicon glyphicon-eye-open mr1"></span>Посмотреть на сайте</a></li>
                    <li><a href="<?=$this->url(
                            array('module'=>'admin', 'controller' => 'pipeline', 'action' => 'add'),
                            false,true
                        )?>"><span class="glyphicon glyphicon-plus mr1"></span>Добавить товар</a></li>
                    <li><a href="<?=$this->url(
                            array('module'=>'admin', 'controller' => 'pipeline', 'action' => 'delete'),
                            'adminEdit'
                        )?>"><span class="glyphicon glyphicon-trash mr1"></span>Удалить товар</a></li>
                    <li class="nav-divider"></li>
                    <li><a href="<?=$this->url(
                            array('module'=>'admin', 'controller' => 'pipeline'),
                            false,true
                        )?>"><span class="glyphicon glyphicon-list mr1"></span>Список товаров</a></li>
                    <li><a href="<?=$this->url(
                            array('module'=>'admin', 'controller' => 'pipeline-property'),
                            false,true
                        )?>"><span class="glyphicon glyphicon-wrench mr1"></span>Список свойств</a></li>
                    <li class="nav-divider"></li>
                    <li><a href="<?=$this->url(
                            array('module'=>'admin', 'controller' => 'pipeline-categories'),
                            false,true
                        )?>"><span class="glyphicon glyphicon-list-alt mr1"></span>Категории товаров</a></li>
                    <li class="nav-divider"></li>
                    <li>
                        <?= $this->form->submit?>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="col-md-9 col-md-offset-1">
        <div class="row">
            <div class="col-md-12">
                <form id="itemEdit" class="" method="post" action="" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-3">
                            <?= $this->form->imageGroup;?>
                        </div>
                        <div class="col-md-8 col-md-offset-1">
                            <?= $this->form->basic;?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <?= $this->form->imageDraftGroup;?>
                        </div>
                        <div class="col-md-8 col-md-offset-1">
                            <?= $this->form->imageTableGroup;?>
                        </div>
                    </div>
                    <ul class="nav nav-tabs nav-justified mtb2"  role="tablist">
                        <li role="presentation" class="active"><a href="#property" aria-controls="property" role="tab" data-toggle="tab">Свойства товара</a></li>
                        <li role="presentation"><a href="#fieldset-desc" aria-controls="fieldset-desc" role="tab" data-toggle="tab">Описание</a></li>
                        <li role="presentation"><a href="#fieldset-seo" aria-controls="fieldset-seo" role="tab" data-toggle="tab">SEO</a></li>
                        <li role="presentation"><a href="#fieldset-additionally" aria-controls="fieldset-additionally" role="tab" data-toggle="tab">Дополнительно</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="property" role="tabpanel">
                            <?=$this->render('pipeline/_property_table_edit.phtml')?>
                        </div>
                        <?= $this->form->desc?>
                        <?= $this->form->seo?>
                        <?= $this->form->additionally?>
                    </div>
                </form>
                <div class="modal fade" id="addPropertyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">Добавить свойство</h4>
                            </div>
                            <div class="modal-body">
                                <form id="pipelinePropertyValueAdd" enctype="multipart/form-data" action="/admin/pipeline-property-value/add" method="post">
                                    <?=$this->formValueAdd->pipelineId?>
                                    <?=$this->formValueAdd->propertyId?>
                                    <div class="ajaxContent" id="ajaxContent">
                                        <?=$this->formValueAdd->value?>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                <button type="submit" class="btn btn-primary" form="pipelinePropertyValueAdd">Сохранить</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>