<?php
/**
 * @var $page Pipeline_Model_Pipeline
 */
$this->title = 'Трубопроводная арматура';
$this->secondary_text = $this->categoryName.'Список товаров';
?>

<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Категория</th>
            <th>Наименование</th>
            <th>Сортировка</th>
            <th>Активность</th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><?=$this->getCategory($page->getCategoryId(),'pipeline')->getTitle()?></td>
                <td><?=$page->getTitle()?></td>
                <td><?=$page->getSorting()?></td>
                <td>
                    <a href="<?= $this->url(array(
                        'module' => 'admin',
                        'controller' => 'pipeline',
                        'action' => 'enable',
                        'id'=>$page->getId()
                    ), 'adminEdit', true, false); ?>" title="<?=($page->getActive() != 0)?'скрыть':'показать'?>">
                        <span class="glyphicon <?=($page->getActive() != 0)?'glyphicon-eye-open':'glyphicon-eye-close'?>"></span>
                    </a>
                </td>
                <td width="150px">
                    <?=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'pipeline',
                        'item_id' => $page->getId(),
                        'item_path' => '/pipeline/'.$page->getFullPath(),
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <?= $this->render('components/_paginator.phtml')?>
<?php else:?>
    <div class="text-center">
        <a href="<?=$this->url(
            array('module'=>'admin', 'controller' => 'pipeline', 'action' => 'add'),
            false,true
        )?>" class="btn btn-success">Добавить товар</a>
    </div>
<?php endif;?>
