<div class="page-header clearfix">
    <h1 class="col-md-9">Трубопроводная арматура</h1>
    <div class="col-md-3 h1">
        <?php if(!empty($this->pages)):?>
            <a href="<?=$this->url(
                array('module'=>'admin', 'controller' => 'pipeline', 'action' => 'add'),
                false,true
            )?>" class="btn btn-success pull-right">Добавить товар</a>
        <?php endif;?>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <ul class="list-group">
            <li class="list-group-item"><a href="<?= $this->url(
                    array('module' => 'admin', 'controller' => 'pipeline-categories', 'action' => 'index'),
                    false, true
                ) ?>">Категории</a></li>
            <li class="list-group-item"><a href="<?= $this->url(
                    array('module' => 'admin', 'controller' => 'pipeline-property', 'action' => 'index'),
                    false, true
                ) ?>">Свойства товаров</a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <?php if(!empty($this->pages)):?>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Категория</th>
                    <th>Наименование</th>
                    <th>Дата создания</th>
                    <th>Сортировка</th>
                    <th>Активность</th>
                    <th></th>
                </tr>
                </thead>
                <?php foreach ($this->pages as $page):?>
                    <tr>
                        <td><?=$page->getId()?></td>
                        <td><?=$this->getCategory($page->getCategoryId(),'pipeline')->getTitle()?></td>
                        <td><?=$page->getTitle()?></td>
                        <td><?=date("Y-m-d", strtotime($page->getCreateDate()));?></td>
                        <td><?=$page->getSorting()?></td>
                        <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
                        <td width="100px">
                            <a href="<?=$this->url(array(
                                'module' => 'admin',
                                'controller' => 'pipeline',
                                'action' => 'edit',
                                'id'=>$page->getId()),
                                'adminEdit', true, false);?>"
                               class="btn btn-default btn-xs"
                               title="Редактировать">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                            <a href="/pipeline/<?=$page->getFullPath().'/';?>"
                               class="btn btn-default btn-xs"
                               title="Просмотр">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </a>
                            <a href="<?=$this->url(array(
                                'module' => 'admin',
                                'controller' => 'pipeline',
                                'action' => 'delete',
                                'id'=>$page->getId()),
                                'adminEdit', true, false);?>"
                               class="btn btn-default btn-xs"
                               title="Удалить">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            </table>
            <?= $this->render('components/_paginator.phtml')?>
        <?php else:?>
            <div class="text-center">
                <a href="<?=$this->url(
                    array('module'=>'admin', 'controller' => 'pipeline', 'action' => 'add'),
                    false,true
                )?>" class="btn btn-success">Добавить товар</a>
            </div>
        <?php endif;?>
    </div>
</div>
