<?php
    $this->title = 'Каталог продукции';
    $this->headTitle($this->title);
    $this->sidebar_headers = false;
?>


<div class="col-md-12">
    <?php foreach ($this->entries as $entry): ?>
        <div class="col-md-3 text-center">
            <a href="<?=$this->url(array('fullPath'=>$entry->fullPath),'catalog',true,false) ?>">
                <img src="/files/images/category/<?=$entry->image;?>" alt="<?=$entry->name?>"/>
                <span><?=$entry->name?></span>
            </a>
        </div>
    <?php endforeach; ?>
</div>
