<?php
    $this->title = 'Каталог продукции';
    $this->headTitle($this->title);
    $this->meta_title = $this->title;
?>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9"><h1><?=$this->title;?></h1></div>
</div>

<div class="row">
    <div class="col-md-9 col-md-push-3">
        <?php foreach ($this->entries as $entry): ?>
            <div class="col-md-3 text-center">
                <a href="">
                    <img src="/files/images/category/<?=$entry->image;?>" alt="<?=$entry->name?>"/>
                    <span><?=$entry->name?></span>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="col-md-3 col-md-pull-9">
        <?= $this->action(
            "index",
            "sidebar",
            "catalog",
            Zend_Controller_Front::getInstance()
                ->getRequest()
                ->getParams()
        );?>
    </div>
</div>
