<a href="/catalog/categories">Категории</a><br/>

<?php $this -> headScript() -> captureStart(); ?>
    $(function(){
       
       $("#search").keyup(function(e){
           $("#autocomplete").empty();
           
           if ( $(this).val().length < 3 ) return true;
           else 
           $.post('/products/findsku', {sku: $(this).val()},
                             function(data){
                                 $("#autocomplete").empty();
                                 if ( data.length > 0 ) for ( i=0; i < data.length; i++ ){
                                     
                                     $("#autocomplete").append("<a href='#' class='autocomplete'>"+data[i]+"</a><br/>");
                                     
                                 } else {
                                     $("#autocomplete").html("Нет совпадений");
                                 }
                                 
                             }, 'json');           
       });
       
       
       
       $("#autocomplete").on('click', '.autocomplete', function(){
           $("#search").val ( $(this).text() );
           $("#search-form").submit();
       });
    });
<?php $this -> headScript() -> captureEnd(); ?>

<form id="search-form">
    <input type="text" name="search" id="search" />
    <div id="autocomplete"></div>
    <input type="submit" />
</form>