<?php
$this->headTitle($this->title);
$this->meta_title = $this->title;
?>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <div class="page-header">
            <h1><?=$this->escape($this->title)?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Заглушки</h3>
                        <p>Заглушки фланцевые стальные, бесшовные, приварные и резьбовые. DIN2617, DIN28011, DIN2527, ANSI B16.5, EN1092-1 и другие</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Отводы</h3>
                        <p>Отводы стальные, бесшовные гнутые, штампосварные и сварные секционные. DIN2605, ANSI B16.9, EN10253.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Переходы</h3>
                        <p>Стальные переходы, концентрические, эксцентрические. DIN2616, ANSI B16.9, EN10253 и другие</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Тройники</h3>
                        <p>Стальные тройники. DIN2615, DIN2618, ANSI B16.9, EN 10253 и другие</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Трубы</h3>
                        <p>Трубы стальные DN 8-100, d 13.5 - 508, DIN2440, DIN2448, EN 10217, EN 10255, EN 10216</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption text-center">
                        <h3>Фланцы</h3>
                        <p>Стальные фланцы воротниковые, приварные, резьбовые, свободные, втулки и кольца.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center mt3">
                    <img src="/images/sections/pipeline-access560x325.png" alt="Трубопроводная арматура"/>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-3 col-md-pull-9">
        <?=$this->render('components/_sidebar_contact_info.phtml')?>
    </div>
</div>