<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <div class="page-header clearfix">
            <h1 class="col-md-10">Производство</h1>
            <div class="col-md-2 h1">
                <a href="<?=$this->url(
                    array('module'=>'admin', 'controller' => 'manufacture', 'action' => 'add'),
                    false,true
                )?>" class="btn btn-success pull-right">Добавить товар</a>
            </div>
        </div>
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Категория</th>
                <th>Заголовок</th>
                <th>Url</th>
                <th>Дата создания</th>
                <th>Сортировка</th>
                <th>Активность</th>
                <th></th>
            </tr>
            </thead>
            <?php foreach ($this->pages as $page):?>
                <tr>
                    <td><?=$page->getId()?></td>
                    <td><?=$this->getManufactureCategory($page->getCategoryId())->getTitle()?></td>
                    <td><?=$page->getTitle()?></td>
                    <td><?=$page->getFullPath()?></td>
                    <td><?=date("Y-m-d", strtotime($page->getCreateDate()));?></td>
                    <td><?=$page->getSorting()?></td>
                    <td><input type="checkbox" value="<?=$page->getActive()?>" <?=($page->getActive() != 0)?'checked':'';?>></td>
                    <td width="100px">
                        <a href="<?=$this->url(array(
                            'module' => 'admin',
                            'controller' => 'manufacture',
                            'action' => 'edit',
                            'id'=>$page->getId()),
                            'adminEdit', true, false);?>"
                           class="btn btn-default btn-xs"
                           title="Редактировать">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="/manufacture/<?=$page->getFullPath().'/';?>"
                           class="btn btn-default btn-xs"
                           title="Просмотр">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        </a>
                        <a href="<?=$this->url(array(
                            'module' => 'admin',
                            'controller' => 'manufacture',
                            'action' => 'delete',
                            'id'=>$page->getId()),
                            'adminEdit', true, false);?>"
                           class="btn btn-default btn-xs"
                           title="Удалить">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
        <?= $this->render('components/_paginator.phtml')?>
    </div>
</div>
