<?php
/**
 * @var $page Manufacture_Model_Manufacture
*/
$this->title = 'Производство';
$this->secondary_text = $this->categoryName.'Список товаров';
?>

<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Категория</th>
        <th>Заголовок</th>
        <th>Сортировка</th>
        <th>Активность</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($this->pages as $page):?>
        <tr class="<?=$this->contextualClassTr($page);?>">
            <td><?=$page->getId()?></td>
            <td><?=$this->getManufactureCategory($page->getCategoryId())->getTitle()?></td>
            <td><?=$page->getTitle()?></td>
            <td><?=$page->getSorting()?></td>
            <td>
                <a href="<?= $this->url(array(
                    'module' => 'admin',
                    'controller' => 'manufacture',
                    'action' => 'enable',
                    'id'=>$page->getId()
                ), null, true); ?>" title="<?=($page->getActive() != 0)?'скрыть':'показать'?>">
                    <span class="glyphicon <?=($page->getActive() != 0)?'glyphicon-eye-open':'glyphicon-eye-close'?>"></span>
                </a>
            </td>
            <td width="150px">
                <?=$this->partial('_button_group_table.phtml', array(
                    'item_controller' => 'manufacture',
                    'item_id' => $page->getId(),
                    'item_path' => '/manufacture/'.$page->getFullPath(),
                    'deleted' => ($page->getDeleted() != 0)? true : false,
                ))?>
            </td>
        </tr>
    <?php endforeach;?>
</table>
<?= $this->render('components/_paginator.phtml')?>
