<?php
/**
 * @var $page Manufacture_Model_Manufacture
*/
$this->title = 'Производство';
$this->secondary_text = $this->categoryName.'Список товаров';
?>
<?php if(!empty($this->pages)):?>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th><span class="glyphicon glyphicon-sort"></span></th>
            <?php if(!$this->categoryName):?>
                <th>Категория</th>
            <?php endif;?>
            <th>Наименование</th>
            <th>Действия</th>
        </tr>
        </thead>
        <?php foreach ($this->pages as $page):?>
            <tr class="<?=$this->contextualClassTr($page);?>">
                <td><?=$page->getId()?></td>
                <td><?=$page->getSorting()?></td>
                <?php if(!$this->categoryName):?>
                    <td><?=$this->getCategory($page->getCategoryId(), 'manufacture')->getTitle()?></td>
                <?php endif;?>
                <td>
                    <?php if($page->getDeleted() != 1):?>
                        <a href="/manufacture/<?=$page->getFullPath();?>" title="Посмотреть на сайте">
                            <?=$page->getTitle()?>
                            <span class="glyphicon glyphicon-link mlr1"></span>
                        </a>
                    <?php else:?>
                        <?=$page->getTitle()?>
                    <?php endif;?>
                </td>
                <td width="150px">
                    <?=$this->partial('_button_group_table.phtml', array(
                        'item_controller' => 'manufacture',
                        'item_id' => $page->getId(),
                        'item_path' => '/manufacture/'.$page->getFullPath(),
                        'active' => ($page->getActive() != 0)? true : false,
                        'deleted' => ($page->getDeleted() != 0)? true : false,
                    ))?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
<?php endif;?>
<div class="pull-left">
    <a href="<?=$this->url(
        array(
            'module'=>'admin',
            'controller' => 'manufacture',
            'action' => 'add',
            'id' => $this->category_id
            ),
        false,true
    )?>" class="btn btn-default">Добавить товар</a>
</div>
<?= $this->render('components/_paginator.phtml')?>

